/*
 * Copyright (C) 2010, 2011, 2012 Freescale Semiconductor, Inc.
 * All rights reserved.
 *
 * This software may be distributed under the terms of the
 * GNU General Public License ("GPL") as published by the Free Software
 * Foundation, either version 2 of that License or (at your option) any
 * later version.
 *
 * THIS SOFTWARE IS PROVIDED BY Freescale Semiconductor ``AS IS'' AND ANY
 * EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL Freescale Semiconductor BE LIABLE FOR ANY
 * DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
 * ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
 * THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */
#ifndef QORIQ_RAW_EVENTS_H
#define QORIQ_RAW_EVENTS_H

/* These fields are common to all event groups */
/* Event group ID */
#define QORIQ_EVENT_GROUP_MASK 0xF8000000
/* bits that indicate event within event group */
#define QORIQ_EVENT_ID_MASK 0x000003FF

/* QorIQ Events is a unique event id for each measurable event.
 * These are used as the perf <cmd> -e rXXXXX raw event values */

/* Base code numbers for the event code */
enum QORIQ_EVENT_BASE {
	QORIQ_EVENT_BASE_START = 0x10000000,
	QORIQ_EVENT_BASE_EPU = QORIQ_EVENT_BASE_START,
	QORIQ_EVENT_BASE_CORENET = 0x20000000,
	QORIQ_EVENT_BASE_DATAPATH = 0x30000000,
	QORIQ_EVENT_BASE_NXC = 0x40000000,
	QORIQ_EVENT_BASE_SCU = 0x50000000,
	QORIQ_EVENT_BASE_CORE = 0x60000000,
	QORIQ_EVENT_BASE_MPIC = 0x70000000,
	QORIQ_EVENT_BASE_RCPM = 0x80000000,
	QORIQ_EVENT_BASE_ELBC = 0x90000000,
	QORIQ_EVENT_BASE_DDR = 0xa0000000,
	QORIQ_EVENT_BASE_NPC = 0xb0000000,
	QORIQ_EVENT_BASE_DDR_COMPLEX = 0xc0000000,
	QORIQ_EVENT_BASE_END = 0xcfffffff,
};

/* All Qoriq Events are prefixed with "QE_" */
enum QORIQ_EVENTS {
	/************************************************************/
	/* EPU events 												*/
	/************************************************************/
	QORIQ_EVENT_EPU_FIRST = QORIQ_EVENT_BASE_EPU + 0x0,
	
	QE_PLATFORM_CYCLES = QORIQ_EVENT_EPU_FIRST,
	QORIQ_EVENT_EPU_LAST = QE_PLATFORM_CYCLES,

	/************************************************************/
	/* Corenet events 											*/
	/************************************************************/

	/**********************************************/
	/* unsupported IDs: > 0 &&  <  64*/
	/**********************************************/
	QORIQ_EVENT_CORENET_FIRST = QORIQ_EVENT_BASE_CORENET + 64,
	/** L3 write miss */
	QE_CNDC_PE_CPC0_WRITE_MISS = QORIQ_EVENT_BASE_CORENET + 64,
	/** L3 write hit */
	QE_CNDC_PE_CPC0_WRITE_HIT = QORIQ_EVENT_BASE_CORENET + 65,
	/** L3 write allocate */
	QE_CNDC_PE_CPC0_WRITE_ALLOC = QORIQ_EVENT_BASE_CORENET + 66,
	/* 67 is reserved */
	/** L3 stash allocate */
	

	/**********************************************/
	/* unsupported IDs: 67    */
	/**********************************************/
	QE_CNDC_PE_CPC0_STASH_ALLOC = QORIQ_EVENT_BASE_CORENET + 68,
	/** L3 read miss */
	QE_CNDC_PE_CPC0_READ_MISS = QORIQ_EVENT_BASE_CORENET + 69,
	/** L3 read hit */
	QE_CNDC_PE_CPC0_READ_HIT = QORIQ_EVENT_BASE_CORENET + 70,
	/** L3 read allocate */
	QE_CNDC_PE_CPC0_READ_ALLOC = QORIQ_EVENT_BASE_CORENET + 71,
	/** L3 other miss */
	QE_CNDC_PE_CPC0_OTHER_MISS = QORIQ_EVENT_BASE_CORENET + 72,
	/** L3 other hit */
	QE_CNDC_PE_CPC0_OTHER_HIT = QORIQ_EVENT_BASE_CORENET + 73,
	/** L3 decorated */
	QE_CNDC_PE_CPC0_DECORATED = QORIQ_EVENT_BASE_CORENET + 74,
	/** L3 castout */
	QE_CNDC_PE_CPC0_CASTOUT = QORIQ_EVENT_BASE_CORENET + 75,
	/** Marked transaction - L3 write miss */
	
	/**********************************************/
	/* unsupported IDs: > 75 &&  < 80*/
	/**********************************************/
	
	QE_CNDC_PE_CPC0_MARKED_WRITE_MISS = QORIQ_EVENT_BASE_CORENET + 80,
	/** Marked transaction - L3 write hit */
	QE_CNDC_PE_CPC0_MARKED_WRITE_HIT = QORIQ_EVENT_BASE_CORENET + 81,
	/** Marked transaction - L3 write allocate */
	QE_CNDC_PE_CPC0_MARKED_WRITE_ALLOC = QORIQ_EVENT_BASE_CORENET + 82,
	/** Marked transaction - L3 stash allocate */
	
	/**********************************************/
	/* unsupported IDs: > 82 &&  < 84 */
	/**********************************************/
	

	QE_CNDC_PE_CPC0_MARKED_STASH_ALLOC = QORIQ_EVENT_BASE_CORENET + 84,
	/** Marked transaction - L3 read miss */
	QE_CNDC_PE_CPC0_MARKED_READ_MISS = QORIQ_EVENT_BASE_CORENET + 85,
	/** Marked transaction - L3 read hit */
	QE_CNDC_PE_CPC0_MARKED_READ_HIT = QORIQ_EVENT_BASE_CORENET + 86,
	/** Marked transaction - L3 read allocate */
	QE_CNDC_PE_CPC0_MARKED_READ_ALLOC = QORIQ_EVENT_BASE_CORENET + 87,
	/** Marked transaction - L3 other miss */
	QE_CNDC_PE_CPC0_MARKED_OTHER_MISS = QORIQ_EVENT_BASE_CORENET + 88,
	/** Marked transaction - L3 other hit */
	QE_CNDC_PE_CPC0_MARKED_OTHER_HIT = QORIQ_EVENT_BASE_CORENET + 89,
	/** Marked transaction - L3 decorated */
	QE_CNDC_PE_CPC0_MARKED_DECORATED = QORIQ_EVENT_BASE_CORENET + 90,
	/** Marked transaction - L3 castout */
	QE_CNDC_PE_CPC0_MARKED_CASTOUT = QORIQ_EVENT_BASE_CORENET + 91,
	/** L3 data write */
	
	/**********************************************/
	/* unsupported IDs: > 91 &&  < 96 */
	/**********************************************/
	
	QE_CNDC_PE_CPC0_DATA_WRITE = QORIQ_EVENT_BASE_CORENET + 96,
	/** L3 data read-modify-write */
	QE_CNDC_PE_CPC0_DATA_RMW = QORIQ_EVENT_BASE_CORENET + 97,
	/** L3 data read */
	QE_CNDC_PE_CPC0_DATA_READ = QORIQ_EVENT_BASE_CORENET + 98,
	/** L3 data access */
	QE_CNDC_PE_CPC0_DATA_ACCESS = QORIQ_EVENT_BASE_CORENET + 99,
	/** Marked transaction - L3 data write */
	QE_CNDC_PE_CPC0_MARKED_DATA_WRITE = QORIQ_EVENT_BASE_CORENET + 100,
	/** Marked transaction - L3 data read-modify-write */
	QE_CNDC_PE_CPC0_MARKED_DATA_RMW = QORIQ_EVENT_BASE_CORENET + 101,
	/** Marked transaction - L3 data read */
	QE_CNDC_PE_CPC0_MARKED_DATA_READ = QORIQ_EVENT_BASE_CORENET + 102,
	/** Marked transaction - L3 data access */
	QE_CNDC_PE_CPC0_MARKED_DATA_ACCESS = QORIQ_EVENT_BASE_CORENET + 103,
	/** L3 write miss */
	
	/**********************************************/
	/* unsupported IDs: > 103 &&  <  128*/
	/**********************************************/
	
	QE_CNDC_PE_CPC1_WRITE_MISS = QORIQ_EVENT_BASE_CORENET + 128,
	/** L3 write hit */
	QE_CNDC_PE_CPC1_WRITE_HIT = QORIQ_EVENT_BASE_CORENET + 129,
	/** L3 write allocate */
	QE_CNDC_PE_CPC1_WRITE_ALLOC = QORIQ_EVENT_BASE_CORENET + 130,
	/** L3 stash allocate */
	
	/**********************************************/
	/* unsupported IDs: > 130 &&  < 132 */
	/**********************************************/
	
	QE_CNDC_PE_CPC1_STASH_ALLOC = QORIQ_EVENT_BASE_CORENET + 132,
	/** L3 read miss */
	QE_CNDC_PE_CPC1_READ_MISS = QORIQ_EVENT_BASE_CORENET + 133,
	/** L3 read hit */
	QE_CNDC_PE_CPC1_READ_HIT = QORIQ_EVENT_BASE_CORENET + 134,
	/** L3 read allocate */
	QE_CNDC_PE_CPC1_READ_ALLOC = QORIQ_EVENT_BASE_CORENET + 135,
	/** L3 other miss */
	QE_CNDC_PE_CPC1_OTHER_MISS = QORIQ_EVENT_BASE_CORENET + 136,
	/** L3 other hit */
	QE_CNDC_PE_CPC1_OTHER_HIT = QORIQ_EVENT_BASE_CORENET + 137,
	/** L3 decorated */
	QE_CNDC_PE_CPC1_DECORATED = QORIQ_EVENT_BASE_CORENET + 138,
	/** L3 castout */
	QE_CNDC_PE_CPC1_CASTOUT = QORIQ_EVENT_BASE_CORENET + 139,
	/** Marked transaction - L3 write miss */
	
	/**********************************************/
	/* unsupported IDs: > 139 &&  < 144 */
	/**********************************************/
	
	QE_CNDC_PE_CPC1_MARKED_WRITE_MISS = QORIQ_EVENT_BASE_CORENET + 144,
	/** Marked transaction - L3 write hit */
	QE_CNDC_PE_CPC1_MARKED_WRITE_HIT = QORIQ_EVENT_BASE_CORENET + 145,
	/** Marked transaction - L3 write allocate */
	QE_CNDC_PE_CPC1_MARKED_WRITE_ALLOC = QORIQ_EVENT_BASE_CORENET + 146,
	/** Marked transaction - L3 stash allocate */
	
	/**********************************************/
	/* unsupported IDs: > 146 &&  <  148*/
	/**********************************************/
	
	QE_CNDC_PE_CPC1_MARKED_STASH_ALLOC = QORIQ_EVENT_BASE_CORENET + 148,
	/** Marked transaction - L3 read miss */
	QE_CNDC_PE_CPC1_MARKED_READ_MISS = QORIQ_EVENT_BASE_CORENET + 149,
	/** Marked transaction - L3 read hit */
	QE_CNDC_PE_CPC1_MARKED_READ_HIT = QORIQ_EVENT_BASE_CORENET + 150,
	/** Marked transaction - L3 read allocate */
	QE_CNDC_PE_CPC1_MARKED_READ_ALLOC = QORIQ_EVENT_BASE_CORENET + 151,
	/** Marked transaction - L3 other miss */
	QE_CNDC_PE_CPC1_MARKED_OTHER_MISS = QORIQ_EVENT_BASE_CORENET + 152,
	/** Marked transaction - L3 other hit */
	QE_CNDC_PE_CPC1_MARKED_OTHER_HIT = QORIQ_EVENT_BASE_CORENET + 153,
	/** Marked transaction - L3 decorated */
	QE_CNDC_PE_CPC1_MARKED_DECORATED = QORIQ_EVENT_BASE_CORENET + 154,
	/** Marked transaction - L3 castout */
	QE_CNDC_PE_CPC1_MARKED_CASTOUT = QORIQ_EVENT_BASE_CORENET + 155,
	/** L3 data write */
	
	/**********************************************/
	/* unsupported IDs: > 155 &&  <  160 */
	/**********************************************/
	
	QE_CNDC_PE_CPC1_DATA_WRITE = QORIQ_EVENT_BASE_CORENET + 160,
	/** L3 data read-modify-write */
	QE_CNDC_PE_CPC1_DATA_RMW = QORIQ_EVENT_BASE_CORENET + 161,
	/** L3 data read */
	QE_CNDC_PE_CPC1_DATA_READ = QORIQ_EVENT_BASE_CORENET + 162,
	/** L3 data access */
	QE_CNDC_PE_CPC1_DATA_ACCESS = QORIQ_EVENT_BASE_CORENET + 163,
	/** Marked transaction - L3 data write */
	QE_CNDC_PE_CPC1_MARKED_DATA_WRITE = QORIQ_EVENT_BASE_CORENET + 164,
	/** Marked transaction - L3 data read-modify-write */
	QE_CNDC_PE_CPC1_MARKED_DATA_RMW = QORIQ_EVENT_BASE_CORENET + 165,
	/** Marked transaction - L3 data read */
	QE_CNDC_PE_CPC1_MARKED_DATA_READ = QORIQ_EVENT_BASE_CORENET + 166,
	/** Marked transaction - L3 data access */
	QE_CNDC_PE_CPC1_MARKED_DATA_ACCESS = QORIQ_EVENT_BASE_CORENET + 167,

	QORIQ_EVENT_CORENET_LAST = QE_CNDC_PE_CPC1_MARKED_DATA_ACCESS,
	
	/************************************************************/
	/* DPAA events 												*/
	/************************************************************/
	QORIQ_EVENT_DATAPATH_FIRST = QORIQ_EVENT_BASE_DATAPATH + 0,
	
	QE_DPAA_PE_QM_DCP0_DEQ_EXCEEDS_THRESHOLD_A = QORIQ_EVENT_DATAPATH_FIRST,
	QE_DPAA_PE_QM_DCP0_DEQ_EXCEEDS_THRESHOLD_B = QORIQ_EVENT_BASE_DATAPATH + 1,
	QE_DPAA_PE_QM_DCP0_DEQ_EXCEEDS_THRESHOLD_C = QORIQ_EVENT_BASE_DATAPATH + 2,
	QE_DPAA_PE_QM_DCP0_DEQ_EXCEEDS_THRESHOLD_D = QORIQ_EVENT_BASE_DATAPATH + 3,
	QE_DPAA_PE_QM_DCP1_DEQ_EXCEEDS_THRESHOLD_A = QORIQ_EVENT_BASE_DATAPATH + 4,
	QE_DPAA_PE_QM_DCP1_DEQ_EXCEEDS_THRESHOLD_B = QORIQ_EVENT_BASE_DATAPATH + 5,
	QE_DPAA_PE_QM_DCP1_DEQ_EXCEEDS_THRESHOLD_C = QORIQ_EVENT_BASE_DATAPATH + 6,
	QE_DPAA_PE_QM_DCP1_DEQ_EXCEEDS_THRESHOLD_D = QORIQ_EVENT_BASE_DATAPATH + 7,
	QE_DPAA_PE_QM_DCP2_DEQ_EXCEEDS_THRESHOLD_A = QORIQ_EVENT_BASE_DATAPATH + 8,
	QE_DPAA_PE_QM_DCP2_DEQ_EXCEEDS_THRESHOLD_B = QORIQ_EVENT_BASE_DATAPATH + 9,
	QE_DPAA_PE_QM_DCP2_DEQ_EXCEEDS_THRESHOLD_C = QORIQ_EVENT_BASE_DATAPATH + 10,
	QE_DPAA_PE_QM_DCP2_DEQ_EXCEEDS_THRESHOLD_D = QORIQ_EVENT_BASE_DATAPATH + 11,
	QE_DPAA_PE_QM_DCP3_DEQ_EXCEEDS_THRESHOLD_A = QORIQ_EVENT_BASE_DATAPATH + 12,
	QE_DPAA_PE_QM_DCP3_DEQ_EXCEEDS_THRESHOLD_B = QORIQ_EVENT_BASE_DATAPATH + 13,
	QE_DPAA_PE_QM_DCP3_DEQ_EXCEEDS_THRESHOLD_C = QORIQ_EVENT_BASE_DATAPATH + 14,
	QE_DPAA_PE_QM_DCP3_DEQ_EXCEEDS_THRESHOLD_D = QORIQ_EVENT_BASE_DATAPATH + 15,
	
	/* unsupported IDs: > 15 < 47 */
	
	QE_DPAA_PE_QM_PFDR_PREFETCH_DENIED = QORIQ_EVENT_BASE_DATAPATH + 47,
	QE_DPAA_PE_QM_USED_PFDR_NO_PREFETCH_READ = QORIQ_EVENT_BASE_DATAPATH + 48,
	QE_DPAA_PE_QM_SFDR_ALLOCATION_SUCCEED = QORIQ_EVENT_BASE_DATAPATH + 49,
	QE_DPAA_PE_QM_SFDR_ALLOCATION_FAILED = QORIQ_EVENT_BASE_DATAPATH + 50,
	QE_DPAA_PE_QM_PARTIALLY_FULL_PFDR_WRITE = QORIQ_EVENT_BASE_DATAPATH + 51,
	QE_DPAA_PE_QM_FQ_TRULY_SCHEDULED_DCPx = QORIQ_EVENT_BASE_DATAPATH + 52,
	QE_DPAA_PE_QM_FQ_TRULY_SCHEDULED_SPx = QORIQ_EVENT_BASE_DATAPATH + 53,
	QE_DPAA_PE_QM_FQ_TRULY_SCHEDULED_RESCH = QORIQ_EVENT_BASE_DATAPATH + 54,
	QE_DPAA_PE_QM_DCP0_ENQ_CMD_RECEIVED = QORIQ_EVENT_BASE_DATAPATH + 55,
	QE_DPAA_PE_QM_DCP1_ENQ_CMD_RECEIVED = QORIQ_EVENT_BASE_DATAPATH + 56,
	QE_DPAA_PE_QM_DCP2_ENQ_CMD_RECEIVED = QORIQ_EVENT_BASE_DATAPATH + 57,
	QE_DPAA_PE_QM_DCP3_ENQ_CMD_RECEIVED = QORIQ_EVENT_BASE_DATAPATH + 58,
	QE_DPAA_PE_QM_SP0_ENQ_CMD_RECEIVED = QORIQ_EVENT_BASE_DATAPATH + 59,
	QE_DPAA_PE_QM_SP1_ENQ_CMD_RECEIVED = QORIQ_EVENT_BASE_DATAPATH + 60,
	QE_DPAA_PE_QM_SP2_ENQ_CMD_RECEIVED = QORIQ_EVENT_BASE_DATAPATH + 61,
	QE_DPAA_PE_QM_SP3_ENQ_CMD_RECEIVED = QORIQ_EVENT_BASE_DATAPATH + 62,
	QE_DPAA_PE_QM_SP4_ENQ_CMD_RECEIVED = QORIQ_EVENT_BASE_DATAPATH + 63,
	QE_DPAA_PE_QM_SP5_ENQ_CMD_RECEIVED = QORIQ_EVENT_BASE_DATAPATH + 64,
	QE_DPAA_PE_QM_SP6_ENQ_CMD_RECEIVED = QORIQ_EVENT_BASE_DATAPATH + 65,
	QE_DPAA_PE_QM_SP7_ENQ_CMD_RECEIVED = QORIQ_EVENT_BASE_DATAPATH + 66,
	QE_DPAA_PE_QM_SP8_ENQ_CMD_RECEIVED = QORIQ_EVENT_BASE_DATAPATH + 67,
	QE_DPAA_PE_QM_SP9_ENQ_CMD_RECEIVED = QORIQ_EVENT_BASE_DATAPATH + 68,
	QE_DPAA_PE_QM_SP0_ENQ_CMD_PULLED_EQCR_FULL = QORIQ_EVENT_BASE_DATAPATH + 69,
	QE_DPAA_PE_QM_SP1_ENQ_CMD_PULLED_EQCR_FULL = QORIQ_EVENT_BASE_DATAPATH + 70,
	QE_DPAA_PE_QM_SP2_ENQ_CMD_PULLED_EQCR_FULL = QORIQ_EVENT_BASE_DATAPATH + 71,
	QE_DPAA_PE_QM_SP3_ENQ_CMD_PULLED_EQCR_FULL = QORIQ_EVENT_BASE_DATAPATH + 72,
	QE_DPAA_PE_QM_SP4_ENQ_CMD_PULLED_EQCR_FULL = QORIQ_EVENT_BASE_DATAPATH + 73,
	QE_DPAA_PE_QM_SP5_ENQ_CMD_PULLED_EQCR_FULL = QORIQ_EVENT_BASE_DATAPATH + 74,
	QE_DPAA_PE_QM_SP6_ENQ_CMD_PULLED_EQCR_FULL = QORIQ_EVENT_BASE_DATAPATH + 75,
	QE_DPAA_PE_QM_SP7_ENQ_CMD_PULLED_EQCR_FULL = QORIQ_EVENT_BASE_DATAPATH + 76,
	QE_DPAA_PE_QM_SP8_ENQ_CMD_PULLED_EQCR_FULL = QORIQ_EVENT_BASE_DATAPATH + 77,
	QE_DPAA_PE_QM_SP9_ENQ_CMD_PULLED_EQCR_FULL = QORIQ_EVENT_BASE_DATAPATH + 78,
	QE_DPAA_PE_QM_DCP0_ENQ_CMD_FIFO_FULL = QORIQ_EVENT_BASE_DATAPATH + 79,
	QE_DPAA_PE_QM_DCP1_ENQ_CMD_FIFO_FULL = QORIQ_EVENT_BASE_DATAPATH + 80,
	QE_DPAA_PE_QM_DCP2_ENQ_CMD_FIFO_FULL = QORIQ_EVENT_BASE_DATAPATH + 81,
	QE_DPAA_PE_QM_DCP3_ENQ_CMD_FIFO_FULL = QORIQ_EVENT_BASE_DATAPATH + 82,
	QE_DPAA_PE_QM_SPx_EQCR_CR_DISPATCH_FIFO_FULL = QORIQ_EVENT_BASE_DATAPATH + 83,
	QE_DPAA_PE_QM_DCP0_DEQ_CMD_FIFO_FULL = QORIQ_EVENT_BASE_DATAPATH + 84,
	QE_DPAA_PE_QM_DCP1_DEQ_CMD_FIFO_FULL = QORIQ_EVENT_BASE_DATAPATH + 85,
	QE_DPAA_PE_QM_DCP2_DEQ_CMD_FIFO_FULL = QORIQ_EVENT_BASE_DATAPATH + 86,
	QE_DPAA_PE_QM_DCP3_DEQ_CMD_FIFO_FULL = QORIQ_EVENT_BASE_DATAPATH + 87,
	QE_DPAA_PE_QM_DCP0_DEQ_RSP_FIFO_FULL = QORIQ_EVENT_BASE_DATAPATH + 88,
	QE_DPAA_PE_QM_DCP1_DEQ_RSP_FIFO_FULL = QORIQ_EVENT_BASE_DATAPATH + 89,
	QE_DPAA_PE_QM_DCP2_DEQ_RSP_FIFO_FULL = QORIQ_EVENT_BASE_DATAPATH + 90,
	QE_DPAA_PE_QM_DCP3_DEQ_RSP_FIFO_FULL = QORIQ_EVENT_BASE_DATAPATH + 91,
	QE_DPAA_PE_QM_SP0_DEQ_CMD_READY_DQRR_FULL = QORIQ_EVENT_BASE_DATAPATH + 92,
	QE_DPAA_PE_QM_SP1_DEQ_CMD_READY_DQRR_FULL = QORIQ_EVENT_BASE_DATAPATH + 93,
	QE_DPAA_PE_QM_SP2_DEQ_CMD_READY_DQRR_FULL = QORIQ_EVENT_BASE_DATAPATH + 94,
	QE_DPAA_PE_QM_SP3_DEQ_CMD_READY_DQRR_FULL = QORIQ_EVENT_BASE_DATAPATH + 95,
	QE_DPAA_PE_QM_SP4_DEQ_CMD_READY_DQRR_FULL = QORIQ_EVENT_BASE_DATAPATH + 96,
	QE_DPAA_PE_QM_SP5_DEQ_CMD_READY_DQRR_FULL = QORIQ_EVENT_BASE_DATAPATH + 97,
	QE_DPAA_PE_QM_SP6_DEQ_CMD_READY_DQRR_FULL = QORIQ_EVENT_BASE_DATAPATH + 98,
	QE_DPAA_PE_QM_SP7_DEQ_CMD_READY_DQRR_FULL = QORIQ_EVENT_BASE_DATAPATH + 99,
	QE_DPAA_PE_QM_SP8_DEQ_CMD_READY_DQRR_FULL = QORIQ_EVENT_BASE_DATAPATH + 100,
	QE_DPAA_PE_QM_SP9_DEQ_CMD_READY_DQRR_FULL = QORIQ_EVENT_BASE_DATAPATH + 101,
	QE_DPAA_PE_QM_DCP0_ENQ_SEQ_DISPATCHED = QORIQ_EVENT_BASE_DATAPATH + 102,
	QE_DPAA_PE_QM_DCP1_ENQ_SEQ_DISPATCHED = QORIQ_EVENT_BASE_DATAPATH + 103,
	QE_DPAA_PE_QM_DCP2_ENQ_SEQ_DISPATCHED = QORIQ_EVENT_BASE_DATAPATH + 104,
	QE_DPAA_PE_QM_DCP3_ENQ_SEQ_DISPATCHED = QORIQ_EVENT_BASE_DATAPATH + 105,
	QE_DPAA_PE_QMAN_SPx_ENQ_SEQ_DISPATCHED = QORIQ_EVENT_BASE_DATAPATH + 106,
	QE_DPAA_PE_QM_DCP0_ENQ_SEQ_DISPATCH_FIFO_FULL = QORIQ_EVENT_BASE_DATAPATH + 107,
	QE_DPAA_PE_QM_DCP1_ENQ_SEQ_DISPATCH_FIFO_FULL = QORIQ_EVENT_BASE_DATAPATH + 108,
	QE_DPAA_PE_QM_DCP2_ENQ_SEQ_DISPATCH_FIFO_FULL = QORIQ_EVENT_BASE_DATAPATH + 109,
	QE_DPAA_PE_QM_DCP3_ENQ_SEQ_DISPATCH_FIFO_FULL = QORIQ_EVENT_BASE_DATAPATH + 110,
	QE_DPAA_PE_QM_SPx_ENQ_SEQ_DISPATCH_FIFO_FULL = QORIQ_EVENT_BASE_DATAPATH + 111,
	QE_DPAA_PE_QM_DCP0_DEQ_SEQ_DELIVERS_1 = QORIQ_EVENT_BASE_DATAPATH + 112,
	QE_DPAA_PE_QM_DCP1_DEQ_SEQ_DELIVERS_1 = QORIQ_EVENT_BASE_DATAPATH + 113,
	QE_DPAA_PE_QM_DCP2_DEQ_SEQ_DELIVERS_1 = QORIQ_EVENT_BASE_DATAPATH + 114,
	QE_DPAA_PE_QM_DCP3_DEQ_SEQ_DELIVERS_1 = QORIQ_EVENT_BASE_DATAPATH + 115,
	QE_DPAA_PE_QM_SPx_DEQ_SEQ_DELIVERS_1 = QORIQ_EVENT_BASE_DATAPATH + 116,
	QE_DPAA_PE_QM_DCP0_DEQ_SEQ_DELIVERS_2 = QORIQ_EVENT_BASE_DATAPATH + 117,
	QE_DPAA_PE_QM_DCP1_DEQ_SEQ_DELIVERS_2 = QORIQ_EVENT_BASE_DATAPATH + 118,
	QE_DPAA_PE_QM_DCP2_DEQ_SEQ_DELIVERS_2 = QORIQ_EVENT_BASE_DATAPATH + 119,
	QE_DPAA_PE_QM_DCP3_DEQ_SEQ_DELIVERS_2 = QORIQ_EVENT_BASE_DATAPATH + 120,
	QE_DPAA_PE_QM_SPx_DEQ_SEQ_DELIVERS_2 = QORIQ_EVENT_BASE_DATAPATH + 121,
	QE_DPAA_PE_QM_DCP0_DEQ_SEQ_DELIVERS_3 = QORIQ_EVENT_BASE_DATAPATH + 122,
	QE_DPAA_PE_QM_DCP1_DEQ_SEQ_DELIVERS_3 = QORIQ_EVENT_BASE_DATAPATH + 123,
	QE_DPAA_PE_QM_DCP2_DEQ_SEQ_DELIVERS_3 = QORIQ_EVENT_BASE_DATAPATH + 124,
	QE_DPAA_PE_QM_DCP3_DEQ_SEQ_DELIVERS_3 = QORIQ_EVENT_BASE_DATAPATH + 125,
	QE_DPAA_PE_QM_SPx_DEQ_SEQ_DELIVERS_3 = QORIQ_EVENT_BASE_DATAPATH + 126,
	QE_DPAA_PE_QM_DCP0_DEQ_CMD_DISPATCH_FIFO_FULL = QORIQ_EVENT_BASE_DATAPATH + 127,
	QE_DPAA_PE_QM_DCP1_DEQ_CMD_DISPATCH_FIFO_FULL = QORIQ_EVENT_BASE_DATAPATH + 128,
	QE_DPAA_PE_QM_DCP2_DEQ_CMD_DISPATCH_FIFO_FULL = QORIQ_EVENT_BASE_DATAPATH + 129,
	QE_DPAA_PE_QM_DCP3_DEQ_CMD_DISPATCH_FIFO_FULL = QORIQ_EVENT_BASE_DATAPATH + 130,
	QE_DPAA_PE_QM_FRAME_IN_ORL = QORIQ_EVENT_BASE_DATAPATH + 131,
	QE_DPAA_PE_QM_FRAME_IN_ORL_ORP_ADVANCE = QORIQ_EVENT_BASE_DATAPATH + 132,
	QE_DPAA_PE_QM_REJECTED_LATE_FRAME = QORIQ_EVENT_BASE_DATAPATH + 133,
	QE_DPAA_PE_QM_ACCEPCTED_LATE_FRAME = QORIQ_EVENT_BASE_DATAPATH + 134,
	QE_DPAA_PE_QM_REJECTED_EARLY_FRAME = QORIQ_EVENT_BASE_DATAPATH + 135,
	QE_DPAA_PE_QM_DCP0_FRAME_ENQ_REJECTED = QORIQ_EVENT_BASE_DATAPATH + 140,
	QE_DPAA_PE_QM_DCP1_FRAME_ENQ_REJECTED = QORIQ_EVENT_BASE_DATAPATH + 141,
	QE_DPAA_PE_QM_DCP2_FRAME_ENQ_REJECTED = QORIQ_EVENT_BASE_DATAPATH + 142,
	QE_DPAA_PE_QM_DCP3_FRAME_ENQ_REJECTED = QORIQ_EVENT_BASE_DATAPATH + 143,
	QE_DPAA_PE_QM_SPx_FRAME_ENQ_REJECTED = QORIQ_EVENT_BASE_DATAPATH + 144,
	QE_DPAA_PE_QM_DCP0_FRAME_ENQ_WRED_REJECTED = QORIQ_EVENT_BASE_DATAPATH + 145,
	QE_DPAA_PE_QM_DCP1_FRAME_ENQ_WRED_REJECTED = QORIQ_EVENT_BASE_DATAPATH + 146,
	QE_DPAA_PE_QM_DCP2_FRAME_ENQ_WRED_REJECTED = QORIQ_EVENT_BASE_DATAPATH + 147,
	QE_DPAA_PE_QM_DCP3_FRAME_ENQ_WRED_REJECTED = QORIQ_EVENT_BASE_DATAPATH + 148,
	QE_DPAA_PE_QM_SPx_FRAME_ENQ_WRED_REJECTED = QORIQ_EVENT_BASE_DATAPATH + 149,
	QE_DPAA_PE_QM_DCP0_FRAME_ENQ_TD_CONG_REJECTED = QORIQ_EVENT_BASE_DATAPATH + 150,
	QE_DPAA_PE_QM_DCP1_FRAME_ENQ_TD_CONG_REJECTED = QORIQ_EVENT_BASE_DATAPATH + 151,
	QE_DPAA_PE_QM_DCP2_FRAME_ENQ_TD_CONG_REJECTED = QORIQ_EVENT_BASE_DATAPATH + 152,
	QE_DPAA_PE_QM_DCP3_FRAME_ENQ_TD_CONG_REJECTED = QORIQ_EVENT_BASE_DATAPATH + 153,
	QE_DPAA_PE_QM_SPx_FRAME_ENQ_TD_CONG_REJECTED = QORIQ_EVENT_BASE_DATAPATH + 154,
	QE_DPAA_PE_QM_DCP0_FRAME_ENQ_TD_FQ_REJECTED = QORIQ_EVENT_BASE_DATAPATH + 155,
	QE_DPAA_PE_QM_DCP1_FRAME_ENQ_TD_FQ_REJECTED = QORIQ_EVENT_BASE_DATAPATH + 156,
	QE_DPAA_PE_QM_DCP2_FRAME_ENQ_TD_FQ_REJECTED = QORIQ_EVENT_BASE_DATAPATH + 157,
	QE_DPAA_PE_QM_DCP3_FRAME_ENQ_TD_FQ_REJECTED = QORIQ_EVENT_BASE_DATAPATH + 158,
	QE_DPAA_PE_QM_SPx_FRAME_ENQ_TD_FQ_REJECTED = QORIQ_EVENT_BASE_DATAPATH + 159,
	QE_DPAA_PE_QM_DCPx_FRAME_ENQ_MARK_01 = QORIQ_EVENT_BASE_DATAPATH + 160,
	QE_DPAA_PE_QM_DCPx_FRAME_ENQ_MARK_10 = QORIQ_EVENT_BASE_DATAPATH + 161,
	QE_DPAA_PE_QM_DCPx_FRAME_ENQ_MARK_11 = QORIQ_EVENT_BASE_DATAPATH + 162,
	QE_DPAA_PE_QM_SPx_FRAME_ENQ_MARK_01 = QORIQ_EVENT_BASE_DATAPATH + 163,
	QE_DPAA_PE_QM_SPx_FRAME_ENQ_MARK_10 = QORIQ_EVENT_BASE_DATAPATH + 164,
	QE_DPAA_PE_QM_SPx_FRAME_ENQ_MARK_11 = QORIQ_EVENT_BASE_DATAPATH + 165,
	QE_DPAA_PE_QM_DCPx_FRAME_DEQ_MARK_01 = QORIQ_EVENT_BASE_DATAPATH + 166,
	QE_DPAA_PE_QM_DCPx_FRAME_DEQ_MARK_10 = QORIQ_EVENT_BASE_DATAPATH + 167,
	QE_DPAA_PE_QM_DCPx_FRAME_DEQ_MARK_11 = QORIQ_EVENT_BASE_DATAPATH + 168,
	QE_DPAA_PE_QM_SPx_FRAME_DEQ_MARK_01 = QORIQ_EVENT_BASE_DATAPATH + 169,
	QE_DPAA_PE_QM_SPx_FRAME_DEQ_MARK_10 = QORIQ_EVENT_BASE_DATAPATH + 170,
	QE_DPAA_PE_QM_SPx_FRAME_DEQ_MARK_11 = QORIQ_EVENT_BASE_DATAPATH + 171,
	QE_DPAA_PE_QM_ORL_FRAME_ENQ_MARK_01 = QORIQ_EVENT_BASE_DATAPATH + 172,
	QE_DPAA_PE_QM_ORL_FRAME_ENQ_MARK_10 = QORIQ_EVENT_BASE_DATAPATH + 173,
	QE_DPAA_PE_QM_ORL_FRAME_ENQ_MARK_11 = QORIQ_EVENT_BASE_DATAPATH + 174,
	
	/**********************************************/
	/* unsupported IDs: > 174 &&  <  192 */
	/**********************************************/
	
	QE_DPAA_PE_BM_FBPR_WRITE_FREELIST_MONITOR_0 = QORIQ_EVENT_BASE_DATAPATH + 192,
	QE_DPAA_PE_BM_FBPR_READ_FREELIST_MONITOR_0 = QORIQ_EVENT_BASE_DATAPATH + 193,
	QE_DPAA_PE_BM_FBPR_WRITE_FREELIST_MONITOR_1 = QORIQ_EVENT_BASE_DATAPATH + 194,
	QE_DPAA_PE_BM_FBPR_READ_FREELIST_MONITOR_1 = QORIQ_EVENT_BASE_DATAPATH + 195,
	QE_DPAA_PE_BM_FBPR_WRITE_FREELIST_MONITOR_2 = QORIQ_EVENT_BASE_DATAPATH + 196,
	QE_DPAA_PE_BM_FBPR_READ_FREELIST_MONITOR_2 = QORIQ_EVENT_BASE_DATAPATH + 197,
	QE_DPAA_PE_BM_FBPR_WRITE_FREELIST_MONITOR_3 = QORIQ_EVENT_BASE_DATAPATH + 198,
	QE_DPAA_PE_BM_FBPR_READ_FREELIST_MONITOR_3 = QORIQ_EVENT_BASE_DATAPATH + 199,
	QE_DPAA_PE_BM_FBPR_WRITE_FREELIST_MONITOR_4 = QORIQ_EVENT_BASE_DATAPATH + 200,
	QE_DPAA_PE_BM_FBPR_READ_FREELIST_MONITOR_4 = QORIQ_EVENT_BASE_DATAPATH + 201,
	QE_DPAA_PE_BM_FBPR_WRITE_FREELIST_MONITOR_5 = QORIQ_EVENT_BASE_DATAPATH + 202,
	QE_DPAA_PE_BM_FBPR_READ_FREELIST_MONITOR_5 = QORIQ_EVENT_BASE_DATAPATH + 203,
	QE_DPAA_PE_BM_FBPR_WRITE_FREELIST_MONITOR_6 = QORIQ_EVENT_BASE_DATAPATH + 204,
	QE_DPAA_PE_BM_FBPR_READ_FREELIST_MONITOR_6 = QORIQ_EVENT_BASE_DATAPATH + 205,
	QE_DPAA_PE_BM_FBPR_WRITE_FREELIST_MONITOR_7 = QORIQ_EVENT_BASE_DATAPATH + 206,
	QE_DPAA_PE_BM_FBPR_READ_FREELIST_MONITOR_7 = QORIQ_EVENT_BASE_DATAPATH + 207,
	QE_DPAA_PE_BM_RELEASE_BUF_EXCEEDS_CMD_MONITOR_0 = QORIQ_EVENT_BASE_DATAPATH + 208,
	QE_DPAA_PE_BM_ACQUIRE_BUF_EXCEEDS_CMD_MONITOR_0 = QORIQ_EVENT_BASE_DATAPATH + 209,
	QE_DPAA_PE_BM_RELEASE_BUF_EXCEEDS_CMD_MONITOR_1 = QORIQ_EVENT_BASE_DATAPATH + 210,
	QE_DPAA_PE_BM_ACQUIRE_BUF_EXCEEDS_CMD_MONITOR_1 = QORIQ_EVENT_BASE_DATAPATH + 211,
	QE_DPAA_PE_BM_RELEASE_BUF_EXCEEDS_CMD_MONITOR_2 = QORIQ_EVENT_BASE_DATAPATH + 212,
	QE_DPAA_PE_BM_ACQUIRE_BUF_EXCEEDS_CMD_MONITOR_2 = QORIQ_EVENT_BASE_DATAPATH + 213,
	QE_DPAA_PE_BM_RELEASE_BUF_EXCEEDS_CMD_MONITOR_3 = QORIQ_EVENT_BASE_DATAPATH + 214,
	QE_DPAA_PE_BM_ACQUIRE_BUF_EXCEEDS_CMD_MONITOR_3 = QORIQ_EVENT_BASE_DATAPATH + 215,
	QE_DPAA_PE_BM_RELEASE_BUF_EXCEEDS_CMD_MONITOR_4 = QORIQ_EVENT_BASE_DATAPATH + 216,
	QE_DPAA_PE_BM_ACQUIRE_BUF_EXCEEDS_CMD_MONITOR_4 = QORIQ_EVENT_BASE_DATAPATH + 217,
	QE_DPAA_PE_BM_RELEASE_BUF_EXCEEDS_CMD_MONITOR_5 = QORIQ_EVENT_BASE_DATAPATH + 218,
	QE_DPAA_PE_BM_ACQUIRE_BUF_EXCEEDS_CMD_MONITOR_5 = QORIQ_EVENT_BASE_DATAPATH + 219,
	QE_DPAA_PE_BM_RELEASE_BUF_EXCEEDS_CMD_MONITOR_6 = QORIQ_EVENT_BASE_DATAPATH + 220,
	QE_DPAA_PE_BM_ACQUIRE_BUF_EXCEEDS_CMD_MONITOR_6 = QORIQ_EVENT_BASE_DATAPATH + 221,
	QE_DPAA_PE_BM_RELEASE_BUF_EXCEEDS_CMD_MONITOR_7 = QORIQ_EVENT_BASE_DATAPATH + 222,
	QE_DPAA_PE_BM_ACQUIRE_BUF_EXCEEDS_CMD_MONITOR_7 = QORIQ_EVENT_BASE_DATAPATH + 223,
	
	/**********************************************/
	/* unsupported IDs: > 223 &&  <  234 */
	/**********************************************/
	
	QE_DPAA_PE_QM_PAMU_PPAACT_CACHE_MISS = QORIQ_EVENT_BASE_DATAPATH + 234,
	QE_DPAA_PE_QM_PAMU_PPAACT_CACHE_HIT = QORIQ_EVENT_BASE_DATAPATH + 235,
	QE_DPAA_PE_QM_PAMU_SPAACT_CACHE_MISS = QORIQ_EVENT_BASE_DATAPATH + 236,
	QE_DPAA_PE_QM_PAMU_SPAACT_CACHE_HIT = QORIQ_EVENT_BASE_DATAPATH + 237,
	QE_DPAA_PE_QM_PAMU_OMT_CACHE_MISS = QORIQ_EVENT_BASE_DATAPATH + 238,
	QE_DPAA_PE_QM_PAMU_OMT_CACHE_HIT = QORIQ_EVENT_BASE_DATAPATH + 239,
	QE_DPAA_PE_QM_PAMU_PPAACT_SNOOP_HIT = QORIQ_EVENT_BASE_DATAPATH + 240,
	QE_DPAA_PE_QM_PAMU_SPAACT_SNOOP_HIT = QORIQ_EVENT_BASE_DATAPATH + 241,
	QE_DPAA_PE_QM_PAMU_OMT_SNOOP_HIT = QORIQ_EVENT_BASE_DATAPATH + 242,
	
	/**********************************************/
	/* unsupported IDs: > 242 &&  < 247 */
	/**********************************************/
	
	QE_DPAA_PE_QM_PAMU_NO_ADDR_TRANS = QORIQ_EVENT_BASE_DATAPATH + 247,
	QE_DPAA_PE_QM_PAMU_WINDOW_ADDR_TRANS = QORIQ_EVENT_BASE_DATAPATH + 248,
	QE_DPAA_PE_QM_PAMU_NO_TRANS = QORIQ_EVENT_BASE_DATAPATH + 249,
	QE_DPAA_PE_QM_PAMU_IMMEDIATE_TRANS = QORIQ_EVENT_BASE_DATAPATH + 250,
	QE_DPAA_PE_QM_PAMU_INDEX_TRANS = QORIQ_EVENT_BASE_DATAPATH + 251,
	
	/**********************************************/
	/* unsupported IDs: > 251 &&  <  264 */
	/**********************************************/
	
	QE_DPAA_PE_PME_MIA_BUSY = QORIQ_EVENT_BASE_DATAPATH + 264,
	QE_DPAA_PE_PME_PMFA_BUSY1 = QORIQ_EVENT_BASE_DATAPATH + 265,
	QE_DPAA_PE_PME_PMFA_BUSY2 = QORIQ_EVENT_BASE_DATAPATH + 266,
	QE_DPAA_PE_PME_PMFA_BUSY3 = QORIQ_EVENT_BASE_DATAPATH + 267,
	QE_DPAA_PE_PME_READ_SYSTEM_BUS = QORIQ_EVENT_BASE_DATAPATH + 268,
	QE_DPAA_PE_PME_WRITE_SYSTEM_BUS = QORIQ_EVENT_BASE_DATAPATH + 269,
	QE_DPAA_PE_PME_HITS_PMFA_CONTEXT_CACHE = QORIQ_EVENT_BASE_DATAPATH + 270,
	QE_DPAA_PE_PME_HITS_PMFA_RESIDUE_CACHE = QORIQ_EVENT_BASE_DATAPATH + 271,
	QE_DPAA_PE_PME_KES_BUSY1 = QORIQ_EVENT_BASE_DATAPATH + 272,
	QE_DPAA_PE_PME_KES_BUSY2 = QORIQ_EVENT_BASE_DATAPATH + 273,
	
	/**********************************************/
	/* unsupported IDs: > 273 &&  < 276 */
	/**********************************************/
	
	QE_DPAA_PE_PME_HITS_DXE_PATTERN_DESCRIPTION = QORIQ_EVENT_BASE_DATAPATH + 276, 
	QE_DPAA_PE_PME_SRE_PREFETCH_SEQ_BUSY1 = QORIQ_EVENT_BASE_DATAPATH + 277,
	QE_DPAA_PE_PME_SRE_PREFETCH_SEQ_BUSY2 = QORIQ_EVENT_BASE_DATAPATH + 278,
	QE_DPAA_PE_PME_SRE_PREFETCH_SEQ_BUSY3 = QORIQ_EVENT_BASE_DATAPATH + 279,
	QE_DPAA_PE_PME_SRE_EXECUTE_SEQ_BUSY1 = QORIQ_EVENT_BASE_DATAPATH + 280,
	QE_DPAA_PE_PME_SRE_EXECUTE_SEQ_BUSY2 = QORIQ_EVENT_BASE_DATAPATH + 281,
	QE_DPAA_PE_PME_SRE_EXECUTE_SEQ_BUSY3 = QORIQ_EVENT_BASE_DATAPATH + 282,
	QE_DPAA_PE_PME_DXE_PREFETCH_SEQ_BUSY1 = QORIQ_EVENT_BASE_DATAPATH + 283,
	QE_DPAA_PE_PME_DXE_PREFETCH_SEQ_BUSY2 = QORIQ_EVENT_BASE_DATAPATH + 284,
	QE_DPAA_PE_PME_DXE_PREFETCH_SEQ_BUSY3 = QORIQ_EVENT_BASE_DATAPATH + 285,
	QE_DPAA_PE_PME_DXE_EXECUTE_SEQ_BUSY1 = QORIQ_EVENT_BASE_DATAPATH + 286,
	QE_DPAA_PE_PME_DXE_EXECUTE_SEQ_BUSY2 = QORIQ_EVENT_BASE_DATAPATH + 287,
	QE_DPAA_PE_SEC4_DEQ_MARK_01 = QORIQ_EVENT_BASE_DATAPATH + 288,
	QE_DPAA_PE_SEC4_DEQ_MARK_10 = QORIQ_EVENT_BASE_DATAPATH + 289,
	QE_DPAA_PE_SEC4_DEQ_MARK_11 = QORIQ_EVENT_BASE_DATAPATH + 290,
	QE_DPAA_PE_SEC4_ENQ_MARK_01 = QORIQ_EVENT_BASE_DATAPATH + 291,
	QE_DPAA_PE_SEC4_ENQ_MARK_10 = QORIQ_EVENT_BASE_DATAPATH + 292,
	QE_DPAA_PE_SEC4_ENQ_MARK_11 = QORIQ_EVENT_BASE_DATAPATH + 293,
	QE_DPAA_PE_SEC4_JOB_INSERT_FROM_QUEUE_INTERFACE = QORIQ_EVENT_BASE_DATAPATH + 294,
	QE_DPAA_PE_SEC4_JOB_INSERT_FROM_RTIC = QORIQ_EVENT_BASE_DATAPATH + 295,
	QE_DPAA_PE_SEC4_JOB_INSERT_FROM_JOB_QUEUE0 = QORIQ_EVENT_BASE_DATAPATH + 296,
	QE_DPAA_PE_SEC4_JOB_INSERT_FROM_JOB_QUEUE1  = QORIQ_EVENT_BASE_DATAPATH + 297,
	QE_DPAA_PE_SEC4_JOB_INSERT_FROM_JOB_QUEUE2 = QORIQ_EVENT_BASE_DATAPATH + 298,
	QE_DPAA_PE_SEC4_JOB_INSERT_FROM_JOB_QUEUE3 = QORIQ_EVENT_BASE_DATAPATH + 299,
	QE_DPAA_PE_SEC4_JOB_TO_DECO0 = QORIQ_EVENT_BASE_DATAPATH + 300,
	QE_DPAA_PE_SEC4_DECO0_IDLE = QORIQ_EVENT_BASE_DATAPATH + 301,
	QE_DPAA_PE_SEC4_DECO0_AWAITS_DMA = QORIQ_EVENT_BASE_DATAPATH + 302,
	QE_DPAA_PE_SEC4_CMD_IN_DECO0 = QORIQ_EVENT_BASE_DATAPATH + 303,
	QE_DPAA_PE_SEC4_JOB_TO_DECO1 = QORIQ_EVENT_BASE_DATAPATH + 304,
	QE_DPAA_PE_SEC4_DECO1_IDLE = QORIQ_EVENT_BASE_DATAPATH + 305,
	QE_DPAA_PE_SEC4_DECO1_AWAITS_DMA = QORIQ_EVENT_BASE_DATAPATH + 306,
	QE_DPAA_PE_SEC4_CMD_IN_DECO1 = QORIQ_EVENT_BASE_DATAPATH + 307,
	QE_DPAA_PE_SEC4_JOB_TO_DECO2 = QORIQ_EVENT_BASE_DATAPATH + 308,
	QE_DPAA_PE_SEC4_DECO2_IDLE = QORIQ_EVENT_BASE_DATAPATH + 309,
	QE_DPAA_PE_SEC4_DECO2_AWAITS_DMA = QORIQ_EVENT_BASE_DATAPATH + 310,
	QE_DPAA_PE_SEC4_CMD_IN_DECO2 = QORIQ_EVENT_BASE_DATAPATH + 311,
	QE_DPAA_PE_SEC4_JOB_TO_DECO3 = QORIQ_EVENT_BASE_DATAPATH + 312,
	QE_DPAA_PE_SEC4_DECO3_IDLE = QORIQ_EVENT_BASE_DATAPATH + 313,
	QE_DPAA_PE_SEC4_DECO3_AWAITS_DMA = QORIQ_EVENT_BASE_DATAPATH + 314,
	QE_DPAA_PE_SEC4_CMD_IN_DECO3 = QORIQ_EVENT_BASE_DATAPATH + 315,
	QE_DPAA_PE_SEC4_JOB_TO_DECO4 = QORIQ_EVENT_BASE_DATAPATH + 316,
	QE_DPAA_PE_SEC4_DECO4_IDLE = QORIQ_EVENT_BASE_DATAPATH + 317,
	QE_DPAA_PE_SEC4_DECO4_AWAITS_DMA = QORIQ_EVENT_BASE_DATAPATH + 318,
	QE_DPAA_PE_SEC4_CMD_IN_DECO4 = QORIQ_EVENT_BASE_DATAPATH + 319,
	
	/**********************************************/
	/* unsupported IDs: > 319 &&  < 330 */
	/**********************************************/
	
	QE_DPAA_PE_SEC4_PAMU_PPAACT_CACHE_MISS = QORIQ_EVENT_BASE_DATAPATH + 330,
	QE_DPAA_PE_SEC4_PAMU_PPAACT_CACHE_HIT = QORIQ_EVENT_BASE_DATAPATH + 331,
	QE_DPAA_PE_SEC4_PAMU_SPAACT_CACHE_MISS = QORIQ_EVENT_BASE_DATAPATH + 332,
	QE_DPAA_PE_SEC4_PAMU_SPAACT_CACHE_HIT = QORIQ_EVENT_BASE_DATAPATH + 333,
	QE_DPAA_PE_SEC4_PAMU_OMT_CACHE_MISS = QORIQ_EVENT_BASE_DATAPATH + 334,
	QE_DPAA_PE_SEC4_PAMU_OMT_CACHE_HIT = QORIQ_EVENT_BASE_DATAPATH + 335,
	QE_DPAA_PE_SEC4_PAMU_PPAACT_SNOOP_HIT = QORIQ_EVENT_BASE_DATAPATH + 336,
	QE_DPAA_PE_SEC4_PAMU_SPAACT_SNOOP_HIT = QORIQ_EVENT_BASE_DATAPATH + 337,
	QE_DPAA_PE_SEC4_PAMU_OMT_SNOOP_HIT = QORIQ_EVENT_BASE_DATAPATH + 338,
	
	/**********************************************/
	/* unsupported IDs: > 338 &&  < 343 */
	/**********************************************/
	
	QE_DPAA_PE_SEC4_PAMU_NO_ADDR_TRANS = QORIQ_EVENT_BASE_DATAPATH + 343,
	QE_DPAA_PE_SEC4_PAMU_WINDOW_ADDR_TRANS = QORIQ_EVENT_BASE_DATAPATH + 344,
	QE_DPAA_PE_SEC4_PAMU_NO_TRANS = QORIQ_EVENT_BASE_DATAPATH + 345,
	QE_DPAA_PE_SEC4_PAMU_IMMEDIATE_TRANS = QORIQ_EVENT_BASE_DATAPATH + 346,
	QE_DPAA_PE_SEC4_PAMU_INDEX_TRANS = QORIQ_EVENT_BASE_DATAPATH + 347,
	
	/**********************************************/
	/* unsupported IDs: > 347 &&  < 352 */
	/**********************************************/
	
	QE_DPAA_PE_FM1_GMAC_USED_RX_FIFO_GE = QORIQ_EVENT_BASE_DATAPATH + 352,
	QE_DPAA_PE_FM1_DTSEC0_USED_RX_FIFO_GE = QORIQ_EVENT_BASE_DATAPATH + 353,
	QE_DPAA_PE_FM1_DTSEC1_USED_RX_FIFO_GE = QORIQ_EVENT_BASE_DATAPATH + 354,
	QE_DPAA_PE_FM1_DTSEC2_USED_RX_FIFO_GE = QORIQ_EVENT_BASE_DATAPATH + 355,
	QE_DPAA_PE_FM1_DTSEC3_USED_RX_FIFO_GE = QORIQ_EVENT_BASE_DATAPATH + 356,
	QE_DPAA_PE_FM1_PAUSE_FOR_GMAC = QORIQ_EVENT_BASE_DATAPATH + 357,
	QE_DPAA_PE_FM1_PAUSE_FOR_DTSEC0 = QORIQ_EVENT_BASE_DATAPATH + 358,
	QE_DPAA_PE_FM1_PAUSE_FOR_DTSEC1 = QORIQ_EVENT_BASE_DATAPATH + 359,
	QE_DPAA_PE_FM1_PAUSE_FOR_DTSEC2 = QORIQ_EVENT_BASE_DATAPATH + 360,
	QE_DPAA_PE_FM1_PAUSE_FOR_DTSEC3 = QORIQ_EVENT_BASE_DATAPATH + 361,
	QE_DPAA_PE_FM1_BMI_TRAP_MARK_01 = QORIQ_EVENT_BASE_DATAPATH + 362,
	QE_DPAA_PE_FM1_BMI_TRAP_MARK_10 = QORIQ_EVENT_BASE_DATAPATH + 363,
	QE_DPAA_PE_FM1_BMI_TRAP_MARK_11 = QORIQ_EVENT_BASE_DATAPATH + 364,
	QE_DPAA_PE_FM1_DEFAULT_QUEUE_USED = QORIQ_EVENT_BASE_DATAPATH + 365,
	QE_DPAA_PE_FM1_KEYGEN_TRAP_MARK_01 = QORIQ_EVENT_BASE_DATAPATH + 366,
	QE_DPAA_PE_FM1_KEYGEN_TRAP_MARK_10 = QORIQ_EVENT_BASE_DATAPATH + 367,
	QE_DPAA_PE_FM1_KEYGEN_TRAP_MARK_11 = QORIQ_EVENT_BASE_DATAPATH + 368,
	QE_DPAA_PE_FM1_PARSER_TRAP_MARK_01 = QORIQ_EVENT_BASE_DATAPATH + 369,
	QE_DPAA_PE_FM1_PARSER_TRAP_MARK_10 = QORIQ_EVENT_BASE_DATAPATH + 370,
	QE_DPAA_PE_FM1_PARSER_TRAP_MARK_11 = QORIQ_EVENT_BASE_DATAPATH + 371,
	QE_DPAA_PE_FM1_CHANGED_TO_RED = QORIQ_EVENT_BASE_DATAPATH + 372,
	QE_DPAA_PE_FM1_CHANGED_TO_YELLOW = QORIQ_EVENT_BASE_DATAPATH + 373,
	QE_DPAA_PE_FM1_POLICER_TRAP_MARK_01 = QORIQ_EVENT_BASE_DATAPATH + 374,
	QE_DPAA_PE_FM1_POLICER_TRAP_MARK_10 = QORIQ_EVENT_BASE_DATAPATH + 375,
	QE_DPAA_PE_FM1_POLICER_TRAP_MARK_11 = QORIQ_EVENT_BASE_DATAPATH + 376,
	QE_DPAA_PE_FM1_CLASSIFIER1_TRAP_MARK_01 = QORIQ_EVENT_BASE_DATAPATH + 377,
	QE_DPAA_PE_FM1_CLASSIFIER1_TRAP_MARK_10 = QORIQ_EVENT_BASE_DATAPATH + 378,
	QE_DPAA_PE_FM1_CLASSIFIER1_TRAP_MARK_11 = QORIQ_EVENT_BASE_DATAPATH + 379,
	QE_DPAA_PE_FM1_CLASSIFIER2_TRAP_MARK_01 = QORIQ_EVENT_BASE_DATAPATH + 380,
	QE_DPAA_PE_FM1_CLASSIFIER2_TRAP_MARK_10 = QORIQ_EVENT_BASE_DATAPATH + 381,
	QE_DPAA_PE_FM1_CLASSIFIER2_TRAP_MARK_11 = QORIQ_EVENT_BASE_DATAPATH + 382,
	
	/**********************************************/
	/* unsupported IDs: > 382 &&  < 384 */
	/**********************************************/
	
	QE_DPAA_PE_FM1_DMA_CMD_QUEUE_EMERGENCY = QORIQ_EVENT_BASE_DATAPATH + 384,
	QE_DPAA_PE_FM1_DMA_READ_BUF_EMERGENCY = QORIQ_EVENT_BASE_DATAPATH + 385,
	QE_DPAA_PE_FM1_DMA_WRITE_BUF_EMERGENCY = QORIQ_EVENT_BASE_DATAPATH + 386,
	QE_DPAA_PE_FM1_DMA_FPM_WAIT_EMERGENCY = QORIQ_EVENT_BASE_DATAPATH + 387,
	QE_DPAA_PE_FM1_DMA_FPM_SOS_EMERGENCY = QORIQ_EVENT_BASE_DATAPATH + 388,
	QE_DPAA_PE_FM1_QMI_TRAP_MARK_01 = QORIQ_EVENT_BASE_DATAPATH + 389,
	QE_DPAA_PE_FM1_QMI_TRAP_MARK_10 = QORIQ_EVENT_BASE_DATAPATH + 390,
	QE_DPAA_PE_FM1_QMI_TRAP_MARK_11 = QORIQ_EVENT_BASE_DATAPATH + 391,
	
	/**********************************************/
	/* unsupported IDs: > 391 &&  < 401 */
	/**********************************************/
	
	QE_DPAA_PE_SEC4_DEQ_MARK_01_DUP = QORIQ_EVENT_BASE_DATAPATH + 401,
	QE_DPAA_PE_SEC4_DEQ_MARK_10_DUP = QORIQ_EVENT_BASE_DATAPATH + 402,
	QE_DPAA_PE_SEC4_DEQ_MARK_11_DUP = QORIQ_EVENT_BASE_DATAPATH + 403,
	QE_DPAA_PE_SEC4_ENQ_MARK_01_DUP = QORIQ_EVENT_BASE_DATAPATH + 404,
	QE_DPAA_PE_SEC4_ENQ_MARK_10_DUP = QORIQ_EVENT_BASE_DATAPATH + 405,
	QE_DPAA_PE_SEC4_ENQ_MARK_11_DUP = QORIQ_EVENT_BASE_DATAPATH + 406,
	QE_DPAA_PE_FM2_DMA_CMD_QUEUE_EMERGENCY = QORIQ_EVENT_BASE_DATAPATH + 407,
	QE_DPAA_PE_FM2_DMA_READ_BUF_EMERGENCY = QORIQ_EVENT_BASE_DATAPATH + 408,
	QE_DPAA_PE_FM2_DMA_WRITE_BUF_EMERGENCY = QORIQ_EVENT_BASE_DATAPATH + 409,
	QE_DPAA_PE_FM2_DMA_FPM_WAIT_EMERGENCY = QORIQ_EVENT_BASE_DATAPATH + 410,
	QE_DPAA_PE_FM2_DMA_FPM_SOS_EMERGENCY = QORIQ_EVENT_BASE_DATAPATH + 411,
	QE_DPAA_PE_FM2_QMI_TRAP_MARK_01 = QORIQ_EVENT_BASE_DATAPATH + 412,
	QE_DPAA_PE_FM2_QMI_TRAP_MARK_10 = QORIQ_EVENT_BASE_DATAPATH + 413,
	QE_DPAA_PE_FM2_QMI_TRAP_MARK_11 = QORIQ_EVENT_BASE_DATAPATH + 414,
	
	/**********************************************/
	/* unsupported IDs: > 414 &&  < 426 */
	/**********************************************/
	
	QE_DPAA_PE_FM1_PAMU_PPAACT_CACHE_MISS = QORIQ_EVENT_BASE_DATAPATH + 426,
	QE_DPAA_PE_FM1_PAMU_PPAACT_CACHE_HIT = QORIQ_EVENT_BASE_DATAPATH + 427,
	QE_DPAA_PE_FM1_PAMU_SPAACT_CACHE_MISS = QORIQ_EVENT_BASE_DATAPATH + 428,
	QE_DPAA_PE_FM1_PAMU_SPAACT_CACHE_HIT = QORIQ_EVENT_BASE_DATAPATH + 429,
	QE_DPAA_PE_FM1_PAMU_OMT_CACHE_MISS = QORIQ_EVENT_BASE_DATAPATH + 430,
	QE_DPAA_PE_FM1_PAMU_OMT_CACHE_HIT = QORIQ_EVENT_BASE_DATAPATH + 431,
	QE_DPAA_PE_FM1_PAMU_PPAACT_SNOOP_HIT = QORIQ_EVENT_BASE_DATAPATH + 432,
	QE_DPAA_PE_FM1_PAMU_SPAACT_SNOOP_HIT = QORIQ_EVENT_BASE_DATAPATH + 433,
	QE_DPAA_PE_FM1_PAMU_OMT_SNOOP_HIT = QORIQ_EVENT_BASE_DATAPATH + 434,
	
	/**********************************************/
	/* unsupported IDs: > 434 &&  < 439 */
	/**********************************************/
	
	QE_DPAA_PE_FM1_PAMU_NO_ADDR_TRANS = QORIQ_EVENT_BASE_DATAPATH + 439,
	QE_DPAA_PE_FM1_PAMU_WINDOW_ADDR_TRANS = QORIQ_EVENT_BASE_DATAPATH + 440,
	QE_DPAA_PE_FM1_PAMU_NO_TRANS = QORIQ_EVENT_BASE_DATAPATH + 441,
	QE_DPAA_PE_FM1_PAMU_IMMEDIATE_TRANS = QORIQ_EVENT_BASE_DATAPATH + 442,
	QE_DPAA_PE_FM1_PAMU_INDEX_TRANS = QORIQ_EVENT_BASE_DATAPATH + 443,
	
	/**********************************************/
	/* unsupported IDs: > 443 &&  < 448 */
	/**********************************************/
	
	QE_DPAA_PE_FM2_GMAC_USED_RX_FIFO_GE = QORIQ_EVENT_BASE_DATAPATH + 448,
	QE_DPAA_PE_FM2_DTSEC0_USED_RX_FIFO_GE = QORIQ_EVENT_BASE_DATAPATH + 449,
	QE_DPAA_PE_FM2_DTSEC1_USED_RX_FIFO_GE = QORIQ_EVENT_BASE_DATAPATH + 450,
	QE_DPAA_PE_FM2_DTSEC2_USED_RX_FIFO_GE = QORIQ_EVENT_BASE_DATAPATH + 451,
	QE_DPAA_PE_FM2_DTSEC3_USED_RX_FIFO_GE = QORIQ_EVENT_BASE_DATAPATH + 452,
	QE_DPAA_PE_FM2_PAUSE_FOR_GMAC = QORIQ_EVENT_BASE_DATAPATH + 453,
	QE_DPAA_PE_FM2_PAUSE_FOR_DTSEC0 = QORIQ_EVENT_BASE_DATAPATH + 454,
	QE_DPAA_PE_FM2_PAUSE_FOR_DTSEC1 = QORIQ_EVENT_BASE_DATAPATH + 455,
	QE_DPAA_PE_FM2_PAUSE_FOR_DTSEC2 = QORIQ_EVENT_BASE_DATAPATH + 456,
	QE_DPAA_PE_FM2_PAUSE_FOR_DTSEC3 = QORIQ_EVENT_BASE_DATAPATH + 457,
	QE_DPAA_PE_FM2_BMI_TRAP_MARK_01 = QORIQ_EVENT_BASE_DATAPATH + 458,
	QE_DPAA_PE_FM2_BMI_TRAP_MARK_10 = QORIQ_EVENT_BASE_DATAPATH + 459,
	QE_DPAA_PE_FM2_BMI_TRAP_MARK_11 = QORIQ_EVENT_BASE_DATAPATH + 460,
	QE_DPAA_PE_FM2_DEFAULT_QUEUE_USED = QORIQ_EVENT_BASE_DATAPATH + 461,
	QE_DPAA_PE_FM2_KEYGEN_TRAP_MARK_01 = QORIQ_EVENT_BASE_DATAPATH + 462,
	QE_DPAA_PE_FM2_KEYGEN_TRAP_MARK_10 = QORIQ_EVENT_BASE_DATAPATH + 463,
	QE_DPAA_PE_FM2_KEYGEN_TRAP_MARK_11 = QORIQ_EVENT_BASE_DATAPATH + 464,
	QE_DPAA_PE_FM2_PARSER_TRAP_MARK_01 = QORIQ_EVENT_BASE_DATAPATH + 465,
	QE_DPAA_PE_FM2_PARSER_TRAP_MARK_10 = QORIQ_EVENT_BASE_DATAPATH + 466,
	QE_DPAA_PE_FM2_PARSER_TRAP_MARK_11 = QORIQ_EVENT_BASE_DATAPATH + 467,
	QE_DPAA_PE_FM2_CHANGED_TO_RED = QORIQ_EVENT_BASE_DATAPATH + 468,
	QE_DPAA_PE_FM2_CHANGED_TO_YELLOW = QORIQ_EVENT_BASE_DATAPATH + 469,
	QE_DPAA_PE_FM2_POLICER_TRAP_MARK_01 = QORIQ_EVENT_BASE_DATAPATH + 470,
	QE_DPAA_PE_FM2_POLICER_TRAP_MARK_10 = QORIQ_EVENT_BASE_DATAPATH + 471,
	QE_DPAA_PE_FM2_POLICER_TRAP_MARK_11 = QORIQ_EVENT_BASE_DATAPATH + 472,
	QE_DPAA_PE_FM2_CLASSIFIER1_TRAP_MARK_01 = QORIQ_EVENT_BASE_DATAPATH + 473,
	QE_DPAA_PE_FM2_CLASSIFIER1_TRAP_MARK_10 = QORIQ_EVENT_BASE_DATAPATH + 474,
	QE_DPAA_PE_FM2_CLASSIFIER1_TRAP_MARK_11 = QORIQ_EVENT_BASE_DATAPATH + 475,
	QE_DPAA_PE_FM2_CLASSIFIER2_TRAP_MARK_01 = QORIQ_EVENT_BASE_DATAPATH + 476,
	QE_DPAA_PE_FM2_CLASSIFIER2_TRAP_MARK_10 = QORIQ_EVENT_BASE_DATAPATH + 477,
	QE_DPAA_PE_FM2_CLASSIFIER2_TRAP_MARK_11 = QORIQ_EVENT_BASE_DATAPATH + 478,
	
	/**********************************************/
	/* unsupported IDs: > 478 &&  < 488 */
	/**********************************************/
	
	QE_DPAA_PE_PME_READ_SYSTEM_BUS_DUP = QORIQ_EVENT_BASE_DATAPATH + 488,
	QE_DPAA_PE_PME_WRITE_SYSTEM_BUS_DUP = QORIQ_EVENT_BASE_DATAPATH + 489,
	
	/**********************************************/
	/* unsupported IDs: > 489 &&  < 522 */
	/**********************************************/
	
	QE_DPAA_PE_FM2_PAMU_PPAACT_CACHE_MISS = QORIQ_EVENT_BASE_DATAPATH + 522,
	QE_DPAA_PE_FM2_PAMU_PPAACT_CACHE_HIT = QORIQ_EVENT_BASE_DATAPATH + 523,
	QE_DPAA_PE_FM2_PAMU_SPAACT_CACHE_MISS = QORIQ_EVENT_BASE_DATAPATH + 524,
	QE_DPAA_PE_FM2_PAMU_SPAACT_CACHE_HIT = QORIQ_EVENT_BASE_DATAPATH + 525,
	QE_DPAA_PE_FM2_PAMU_OMT_CACHE_MISS = QORIQ_EVENT_BASE_DATAPATH + 526,
	QE_DPAA_PE_FM2_PAMU_OMT_CACHE_HIT = QORIQ_EVENT_BASE_DATAPATH + 527,
	QE_DPAA_PE_FM2_PAMU_PPAACT_SNOOP_HIT = QORIQ_EVENT_BASE_DATAPATH + 528,
	QE_DPAA_PE_FM2_PAMU_SPAACT_SNOOP_HIT = QORIQ_EVENT_BASE_DATAPATH + 529,
	QE_DPAA_PE_FM2_PAMU_OMT_SNOOP_HIT = QORIQ_EVENT_BASE_DATAPATH + 530,
	
	/**********************************************/
	/* unsupported IDs: > 530 &&  < 535 */
	/**********************************************/
	
	QE_DPAA_PE_FM2_PAMU_NO_ADDR_TRANS = QORIQ_EVENT_BASE_DATAPATH + 535,
	QE_DPAA_PE_FM2_PAMU_WINDOW_ADDR_TRANS = QORIQ_EVENT_BASE_DATAPATH + 536,
	QE_DPAA_PE_FM2_PAMU_NO_TRANS = QORIQ_EVENT_BASE_DATAPATH + 537,
	QE_DPAA_PE_FM2_PAMU_IMMEDIATE_TRANS = QORIQ_EVENT_BASE_DATAPATH + 538,
	QE_DPAA_PE_FM2_PAMU_INDEX_TRANS = QORIQ_EVENT_BASE_DATAPATH + 539,
	
	/**********************************************/
	/* unsupported IDs: > 539 &&  < 544 */
	/**********************************************/
	
	QE_DPAA_PE_QM_DCP0_DEQ_EXCEEDS_THRESHOLD_A_DUP = QORIQ_EVENT_BASE_DATAPATH + 544,
	QE_DPAA_PE_QM_DCP0_DEQ_EXCEEDS_THRESHOLD_B_DUP = QORIQ_EVENT_BASE_DATAPATH + 545,
	QE_DPAA_PE_QM_DCP0_DEQ_EXCEEDS_THRESHOLD_C_DUP = QORIQ_EVENT_BASE_DATAPATH + 546,
	QE_DPAA_PE_QM_DCP0_DEQ_EXCEEDS_THRESHOLD_D_DUP = QORIQ_EVENT_BASE_DATAPATH + 547,
	
	/**********************************************/
	/* unsupported IDs: > 547 &&  < 552 */
	/**********************************************/
	
	QE_DPAA_PE_QM_DCP0_ENQ_CMD_RECEIVED_DUP = QORIQ_EVENT_BASE_DATAPATH + 552,
	QE_DPAA_PE_QM_DCP0_ENQ_CMD_FIFO_FULL_DUP = QORIQ_EVENT_BASE_DATAPATH + 553,
	QE_DPAA_PE_QM_DCP0_DEQ_CMD_FIFO_FULL_DUP = QORIQ_EVENT_BASE_DATAPATH + 554,
	QE_DPAA_PE_QM_DCP0_DEQ_RSP_FIFO_FULL_DUP = QORIQ_EVENT_BASE_DATAPATH + 555,
	QE_DPAA_PE_QM_DCP0_ENQ_SEQ_DISPATCH_DUP = QORIQ_EVENT_BASE_DATAPATH + 556,
	QE_DPAA_PE_QM_DCP0_ENQ_SEQ_DISPATCH_FIFO_FULL_DUP = QORIQ_EVENT_BASE_DATAPATH + 557,
	QE_DPAA_PE_QM_DCP0_DEQ_SEQ_DELIVERS_1_DUP = QORIQ_EVENT_BASE_DATAPATH + 558,
	QE_DPAA_PE_QM_DCP0_DEQ_SEQ_DELIVERS_2_DUP = QORIQ_EVENT_BASE_DATAPATH + 559,
	QE_DPAA_PE_QM_DCP0_DEQ_SEQ_DELIVERS_3_DUP = QORIQ_EVENT_BASE_DATAPATH + 560,
	QE_DPAA_PE_QM_DCP0_DEQ_CMD_DISPATCH_FIFO_FULL_DUP = QORIQ_EVENT_BASE_DATAPATH + 561,
	QE_DPAA_PE_QM_DCP0_FRAME_ENQ_REJECTED_DUP = QORIQ_EVENT_BASE_DATAPATH + 562,
	QE_DPAA_PE_QM_DCP0_FRAME_ENQ_WRED_REJECTED_DUP = QORIQ_EVENT_BASE_DATAPATH + 563,
	QE_DPAA_PE_QM_DCP0_FRAME_ENQ_TD_CONG_REJECTED_DUP = QORIQ_EVENT_BASE_DATAPATH + 564,
	QE_DPAA_PE_QM_DCP0_FRAME_ENQ_TD_FQ_REJECTED_DUP = QORIQ_EVENT_BASE_DATAPATH + 565,
	QE_DPAA_PE_QM_DCPx_FRAME_ENQ_MARK_01_DUP = QORIQ_EVENT_BASE_DATAPATH + 566,
	QE_DPAA_PE_QM_DCPx_FRAME_ENQ_MARK_10_DUP = QORIQ_EVENT_BASE_DATAPATH + 567,
	QE_DPAA_PE_QM_DCPx_FRAME_ENQ_MARK_11_DUP = QORIQ_EVENT_BASE_DATAPATH + 568,
	QE_DPAA_PE_QM_DCPx_FRAME_DEQ_MARK_01_DUP = QORIQ_EVENT_BASE_DATAPATH + 569,
	QE_DPAA_PE_QM_DCPx_FRAME_DEQ_MARK_10_DUP = QORIQ_EVENT_BASE_DATAPATH + 570,
	QE_DPAA_PE_QM_DCPx_FRAME_DEQ_MARK_11_DUP = QORIQ_EVENT_BASE_DATAPATH + 571,
	QE_DPAA_PE_QM_ORL_FRAME_ENQ_MARK_01_DUP = QORIQ_EVENT_BASE_DATAPATH + 572,
	QE_DPAA_PE_QM_ORL_FRAME_ENQ_MARK_10_DUP = QORIQ_EVENT_BASE_DATAPATH + 573,
	QE_DPAA_PE_QM_ORL_FRAME_ENQ_MARK_11_DUP = QORIQ_EVENT_BASE_DATAPATH + 574,
	QE_DPAA_PE_QM_DCP1_DEQ_EXCEEDS_THRESHOLD_A_DUP = QORIQ_EVENT_BASE_DATAPATH + 576,
	QE_DPAA_PE_QM_DCP1_DEQ_EXCEEDS_THRESHOLD_B_DUP = QORIQ_EVENT_BASE_DATAPATH + 577,
	QE_DPAA_PE_QM_DCP1_DEQ_EXCEEDS_THRESHOLD_C_DUP = QORIQ_EVENT_BASE_DATAPATH + 578,
	QE_DPAA_PE_QM_DCP1_DEQ_EXCEEDS_THRESHOLD_D_DUP = QORIQ_EVENT_BASE_DATAPATH + 579,
	
	/**********************************************/
	/* unsupported IDs: > 579 &&  < 584 */
	/**********************************************/
	
	QE_DPAA_PE_QM_DCP1_ENQ_CMD_RECEIVED_DUP = QORIQ_EVENT_BASE_DATAPATH + 584,
	QE_DPAA_PE_QM_DCP1_ENQ_CMD_FIFO_FULL_DUP = QORIQ_EVENT_BASE_DATAPATH + 585,
	QE_DPAA_PE_QM_DCP1_DEQ_CMD_FIFO_FULL_DUP = QORIQ_EVENT_BASE_DATAPATH + 586,
	QE_DPAA_PE_QM_DCP1_DEQ_RSP_FIFO_FULL_DUP = QORIQ_EVENT_BASE_DATAPATH + 587,
	QE_DPAA_PE_QM_DCP1_ENQ_SEQ_DISPATCH_DUP = QORIQ_EVENT_BASE_DATAPATH + 588,
	QE_DPAA_PE_QM_DCP1_ENQ_SEQ_DISPATCH_FIFO_FULL_DUP = QORIQ_EVENT_BASE_DATAPATH + 589,
	QE_DPAA_PE_QM_DCP1_DEQ_SEQ_DELIVERS_1_DUP = QORIQ_EVENT_BASE_DATAPATH + 590,
	QE_DPAA_PE_QM_DCP1_DEQ_SEQ_DELIVERS_2_DUP = QORIQ_EVENT_BASE_DATAPATH + 591,
	QE_DPAA_PE_QM_DCP1_DEQ_SEQ_DELIVERS_3_DUP = QORIQ_EVENT_BASE_DATAPATH + 592,
	QE_DPAA_PE_QM_DCP1_DEQ_CMD_DISPATCH_FIFO_FULL_DUP = QORIQ_EVENT_BASE_DATAPATH + 593,
	QE_DPAA_PE_QM_DCP1_FRAME_ENQ_REJECTED_DUP = QORIQ_EVENT_BASE_DATAPATH + 594,
	QE_DPAA_PE_QM_DCP1_FRAME_ENQ_WRED_REJECTED_DUP = QORIQ_EVENT_BASE_DATAPATH + 595,
	QE_DPAA_PE_QM_DCP1_FRAME_ENQ_TD_CONG_REJECTED_DUP = QORIQ_EVENT_BASE_DATAPATH + 596,
	QE_DPAA_PE_QM_DCP1_FRAME_ENQ_TD_FQ_REJECTED_DUP = QORIQ_EVENT_BASE_DATAPATH + 597,
	QE_DPAA_PE_QM_DCPx_FRAME_ENQ_MARK_01_DUP2 = QORIQ_EVENT_BASE_DATAPATH + 598,
	QE_DPAA_PE_QM_DCPx_FRAME_ENQ_MARK_10_DUP2 = QORIQ_EVENT_BASE_DATAPATH + 599,
	QE_DPAA_PE_QM_DCPx_FRAME_ENQ_MARK_11_DUP2 = QORIQ_EVENT_BASE_DATAPATH + 600,
	QE_DPAA_PE_QM_DCPx_FRAME_DEQ_MARK_01_DUP2 = QORIQ_EVENT_BASE_DATAPATH + 601,
	QE_DPAA_PE_QM_DCPx_FRAME_DEQ_MARK_10_DUP2 = QORIQ_EVENT_BASE_DATAPATH + 602,
	QE_DPAA_PE_QM_DCPx_FRAME_DEQ_MARK_11_DUP2 = QORIQ_EVENT_BASE_DATAPATH + 603,
	QE_DPAA_PE_QM_ORL_FRAME_ENQ_MARK_01_DUP2 = QORIQ_EVENT_BASE_DATAPATH + 604,
	QE_DPAA_PE_QM_ORL_FRAME_ENQ_MARK_10_DUP2 = QORIQ_EVENT_BASE_DATAPATH + 605,
	QE_DPAA_PE_QM_ORL_FRAME_ENQ_MARK_11_DUP2 = QORIQ_EVENT_BASE_DATAPATH + 606,
	
	/**********************************************/
	/* unsupported IDs: > 606  &&  < 608 */
	/**********************************************/
	
	QE_DPAA_PE_QM_DCP2_DEQ_EXCEEDS_THRESHOLD_A_DUP = QORIQ_EVENT_BASE_DATAPATH + 608,
	QE_DPAA_PE_QM_DCP2_DEQ_EXCEEDS_THRESHOLD_B_DUP = QORIQ_EVENT_BASE_DATAPATH + 609,
	QE_DPAA_PE_QM_DCP2_DEQ_EXCEEDS_THRESHOLD_C_DUP = QORIQ_EVENT_BASE_DATAPATH + 610,
	QE_DPAA_PE_QM_DCP2_DEQ_EXCEEDS_THRESHOLD_D_DUP = QORIQ_EVENT_BASE_DATAPATH + 611,
	
	/**********************************************/
	/* unsupported IDs: > 611 &&  < 616 */
	/**********************************************/
	
	QE_DPAA_PE_QM_DCP2_ENQ_CMD_RECEIVED_DUP = QORIQ_EVENT_BASE_DATAPATH + 616,
	QE_DPAA_PE_QM_DCP2_ENQ_CMD_FIFO_FULL_DUP = QORIQ_EVENT_BASE_DATAPATH + 617,
	QE_DPAA_PE_QM_DCP2_DEQ_CMD_FIFO_FULL_DUP = QORIQ_EVENT_BASE_DATAPATH + 618,
	QE_DPAA_PE_QM_DCP2_DEQ_RSP_FIFO_FULL_DUP = QORIQ_EVENT_BASE_DATAPATH + 619,
	QE_DPAA_PE_QM_DCP2_ENQ_SEQ_DISPATCH_DUP = QORIQ_EVENT_BASE_DATAPATH + 620,
	QE_DPAA_PE_QM_DCP2_ENQ_SEQ_DISPATCH_FIFO_FULL_DUP = QORIQ_EVENT_BASE_DATAPATH + 621,
	QE_DPAA_PE_QM_DCP2_DEQ_SEQ_DELIVERS_1_DUP = QORIQ_EVENT_BASE_DATAPATH + 622,
	QE_DPAA_PE_QM_DCP2_DEQ_SEQ_DELIVERS_2_DUP = QORIQ_EVENT_BASE_DATAPATH + 623,
	QE_DPAA_PE_QM_DCP2_DEQ_SEQ_DELIVERS_3_DUP = QORIQ_EVENT_BASE_DATAPATH + 624,
	QE_DPAA_PE_QM_DCP2_DEQ_CMD_DISPATCH_FIFO_FULL_DUP = QORIQ_EVENT_BASE_DATAPATH + 625,
	QE_DPAA_PE_QM_DCP2_FRAME_ENQ_REJECTED_DUP = QORIQ_EVENT_BASE_DATAPATH + 626,
	QE_DPAA_PE_QM_DCP2_FRAME_ENQ_WRED_REJECTED_DUP = QORIQ_EVENT_BASE_DATAPATH + 627,
	QE_DPAA_PE_QM_DCP2_FRAME_ENQ_TD_CONG_REJECTED_DUP = QORIQ_EVENT_BASE_DATAPATH + 628,
	QE_DPAA_PE_QM_DCP2_FRAME_ENQ_TD_FQ_REJECTED_DUP = QORIQ_EVENT_BASE_DATAPATH + 629,
	QE_DPAA_PE_QM_DCPx_FRAME_ENQ_MARK_01_DUP3 = QORIQ_EVENT_BASE_DATAPATH + 630,
	QE_DPAA_PE_QM_DCPx_FRAME_ENQ_MARK_10_DUP3 = QORIQ_EVENT_BASE_DATAPATH + 631,
	QE_DPAA_PE_QM_DCPx_FRAME_ENQ_MARK_11_DUP3 = QORIQ_EVENT_BASE_DATAPATH + 632,
	QE_DPAA_PE_QM_DCPx_FRAME_DEQ_MARK_01_DUP3 = QORIQ_EVENT_BASE_DATAPATH + 633,
	QE_DPAA_PE_QM_DCPx_FRAME_DEQ_MARK_10_DUP3 = QORIQ_EVENT_BASE_DATAPATH + 634,
	QE_DPAA_PE_QM_DCPx_FRAME_DEQ_MARK_11_DUP3 = QORIQ_EVENT_BASE_DATAPATH + 635,
	QE_DPAA_PE_QM_ORL_FRAME_ENQ_MARK_01_DUP3 = QORIQ_EVENT_BASE_DATAPATH + 636,
	QE_DPAA_PE_QM_ORL_FRAME_ENQ_MARK_10_DUP3 = QORIQ_EVENT_BASE_DATAPATH + 637,
	QE_DPAA_PE_QM_ORL_FRAME_ENQ_MARK_11_DUP3 = QORIQ_EVENT_BASE_DATAPATH + 638,
	
	/**********************************************/
	/* unsupported IDs: > 638 &&  < 640 */
	/**********************************************/
	
	QE_DPAA_PE_QM_DCP3_DEQ_EXCEEDS_THRESHOLD_A_DUP = QORIQ_EVENT_BASE_DATAPATH + 640,
	QE_DPAA_PE_QM_DCP3_DEQ_EXCEEDS_THRESHOLD_B_DUP = QORIQ_EVENT_BASE_DATAPATH + 641,
	QE_DPAA_PE_QM_DCP3_DEQ_EXCEEDS_THRESHOLD_C_DUP = QORIQ_EVENT_BASE_DATAPATH + 642,
	QE_DPAA_PE_QM_DCP3_DEQ_EXCEEDS_THRESHOLD_D_DUP = QORIQ_EVENT_BASE_DATAPATH + 643,
	
	/**********************************************/
	/* unsupported IDs: > 643 &&  < 648 */
	/**********************************************/
	
	QE_DPAA_PE_QM_DCP3_ENQ_CMD_RECEIVED_DUP = QORIQ_EVENT_BASE_DATAPATH + 648,
	QE_DPAA_PE_QM_DCP3_ENQ_CMD_FIFO_FULL_DUP = QORIQ_EVENT_BASE_DATAPATH + 649,
	QE_DPAA_PE_QM_DCP3_DEQ_CMD_FIFO_FULL_DUP = QORIQ_EVENT_BASE_DATAPATH + 650,
	QE_DPAA_PE_QM_DCP3_DEQ_RSP_FIFO_FULL_DUP = QORIQ_EVENT_BASE_DATAPATH + 651,
	QE_DPAA_PE_QM_DCP3_ENQ_SEQ_DISPATCH_DUP = QORIQ_EVENT_BASE_DATAPATH + 652,
	QE_DPAA_PE_QM_DCP3_ENQ_SEQ_DISPATCH_FIFO_FULL_DUP = QORIQ_EVENT_BASE_DATAPATH + 653,
	QE_DPAA_PE_QM_DCP3_DEQ_SEQ_DELIVERS_1_DUP = QORIQ_EVENT_BASE_DATAPATH + 654,
	QE_DPAA_PE_QM_DCP3_DEQ_SEQ_DELIVERS_2_DUP = QORIQ_EVENT_BASE_DATAPATH + 655,
	QE_DPAA_PE_QM_DCP3_DEQ_SEQ_DELIVERS_3_DUP = QORIQ_EVENT_BASE_DATAPATH + 656,
	QE_DPAA_PE_QM_DCP3_DEQ_CMD_DISPATCH_FIFO_FULL_DUP = QORIQ_EVENT_BASE_DATAPATH + 657,
	QE_DPAA_PE_QM_DCP3_FRAME_ENQ_REJECTED_DUP = QORIQ_EVENT_BASE_DATAPATH + 658,
	QE_DPAA_PE_QM_DCP3_FRAME_ENQ_WRED_REJECTED_DUP = QORIQ_EVENT_BASE_DATAPATH + 659,
	QE_DPAA_PE_QM_DCP3_FRAME_ENQ_TD_CONG_REJECTED_DUP = QORIQ_EVENT_BASE_DATAPATH + 660,
	QE_DPAA_PE_QM_DCP3_FRAME_ENQ_TD_FQ_REJECTED_DUP = QORIQ_EVENT_BASE_DATAPATH + 661,
	QE_DPAA_PE_QM_DCPx_FRAME_ENQ_MARK_01_DUP4 = QORIQ_EVENT_BASE_DATAPATH + 662,
	QE_DPAA_PE_QM_DCPx_FRAME_ENQ_MARK_10_DUP4 = QORIQ_EVENT_BASE_DATAPATH + 663,
	QE_DPAA_PE_QM_DCPx_FRAME_ENQ_MARK_11_DUP4 = QORIQ_EVENT_BASE_DATAPATH + 664,
	QE_DPAA_PE_QM_DCPx_FRAME_DEQ_MARK_01_DUP4 = QORIQ_EVENT_BASE_DATAPATH + 665,
	QE_DPAA_PE_QM_DCPx_FRAME_DEQ_MARK_10_DUP4 = QORIQ_EVENT_BASE_DATAPATH + 666,
	QE_DPAA_PE_QM_DCPx_FRAME_DEQ_MARK_11_DUP4 = QORIQ_EVENT_BASE_DATAPATH + 667,
	QE_DPAA_PE_QM_ORL_FRAME_ENQ_MARK_01_DUP4 = QORIQ_EVENT_BASE_DATAPATH + 668,
	QE_DPAA_PE_QM_ORL_FRAME_ENQ_MARK_10_DUP4 = QORIQ_EVENT_BASE_DATAPATH + 669,
	QE_DPAA_PE_QM_ORL_FRAME_ENQ_MARK_11_DUP4 = QORIQ_EVENT_BASE_DATAPATH + 670,
	
	/**********************************************/
	/* unsupported IDs: > 670 &&  < 676 */
	/**********************************************/
	
	QE_DPAA_PE_QM_SPx_EQCR_CR_DISPATCH_FIFO_FULL_DUP = QORIQ_EVENT_BASE_DATAPATH + 676,
	QE_DPAA_PE_QMAN_SPx_ENQ_SEQ_DISPATCHED_DUP = QORIQ_EVENT_BASE_DATAPATH + 677,
	QE_DPAA_PE_QM_SPx_ENQ_SEQ_DISPATCH_FIFO_FULL_DUP = QORIQ_EVENT_BASE_DATAPATH + 678,
	QE_DPAA_PE_QM_SPx_DEQ_SEQ_DELIVERS_1_DUP = QORIQ_EVENT_BASE_DATAPATH + 679,
	QE_DPAA_PE_QM_SPx_DEQ_SEQ_DELIVERS_2_DUP = QORIQ_EVENT_BASE_DATAPATH + 680,
	QE_DPAA_PE_QM_SPx_DEQ_SEQ_DELIVERS_3_DUP = QORIQ_EVENT_BASE_DATAPATH + 681,
	QE_DPAA_PE_QM_SPx_FRAME_ENQ_REJECTED_DUP = QORIQ_EVENT_BASE_DATAPATH + 682,
	QE_DPAA_PE_QM_SPx_FRAME_ENQ_WRED_REJECTED_DUP = QORIQ_EVENT_BASE_DATAPATH + 683,
	QE_DPAA_PE_QM_SPx_FRAME_ENQ_TD_CONG_REJECTED_DUP = QORIQ_EVENT_BASE_DATAPATH + 684,
	QE_DPAA_PE_QM_SPx_FRAME_ENQ_TD_FQ_REJECTED_DUP = QORIQ_EVENT_BASE_DATAPATH + 685,
	QE_DPAA_PE_QM_SPx_FRAME_ENQ_MARK_01_DUP = QORIQ_EVENT_BASE_DATAPATH + 686,
	QE_DPAA_PE_QM_SPx_FRAME_ENQ_MARK_10_DUP = QORIQ_EVENT_BASE_DATAPATH + 687,
	QE_DPAA_PE_QM_SPx_FRAME_ENQ_MARK_11_DUP = QORIQ_EVENT_BASE_DATAPATH + 688,
	QE_DPAA_PE_QM_SPx_FRAME_DEQ_MARK_01_DUP = QORIQ_EVENT_BASE_DATAPATH + 689,
	QE_DPAA_PE_QM_SPx_FRAME_DEQ_MARK_10_DUP = QORIQ_EVENT_BASE_DATAPATH + 690,
	QE_DPAA_PE_QM_SPx_FRAME_DEQ_MARK_11_DUP = QORIQ_EVENT_BASE_DATAPATH + 691,
	QE_DPAA_PE_QM_ORL_FRAME_ENQ_MARK_01_DUP5 = QORIQ_EVENT_BASE_DATAPATH + 692,
	QE_DPAA_PE_QM_ORL_FRAME_ENQ_MARK_10_DUP5 = QORIQ_EVENT_BASE_DATAPATH + 693,
	QE_DPAA_PE_QM_ORL_FRAME_ENQ_MARK_11_DUP5 = QORIQ_EVENT_BASE_DATAPATH + 694,
	
	/**********************************************/
	/* unsupported IDs: > 694 &&  < 715 */
	/**********************************************/
	
	QE_DPAA_PE_QM_PFDR_PREFETCH_DENIED_DUP = QORIQ_EVENT_BASE_DATAPATH + 715,
	QE_DPAA_PE_QM_USED_PFDR_NO_PREFETCH_READ_DUP = QORIQ_EVENT_BASE_DATAPATH + 716,
	QE_DPAA_PE_QM_SFDR_ALLOCATION_SUCCEED_DUP = QORIQ_EVENT_BASE_DATAPATH + 717,
	QE_DPAA_PE_QM_SFDR_ALLOCATION_FAILED_DUP = QORIQ_EVENT_BASE_DATAPATH + 718,
	QE_DPAA_PE_QM_PARTIALLY_FULL_PFDR_WRITE_DUP = QORIQ_EVENT_BASE_DATAPATH + 719,
	QE_DPAA_PE_QM_FQ_TRULY_SCHEDULED_DCPx_DUP = QORIQ_EVENT_BASE_DATAPATH + 720,
	QE_DPAA_PE_QM_FQ_TRULY_SCHEDULED_SPx_DUP = QORIQ_EVENT_BASE_DATAPATH + 721,
	QE_DPAA_PE_QM_FQ_TRULY_SCHEDULED_RESCH_DUP = QORIQ_EVENT_BASE_DATAPATH + 722,
	QE_DPAA_PE_QM_FRAME_IN_ORL_DUP = QORIQ_EVENT_BASE_DATAPATH + 723,
	QE_DPAA_PE_QM_FRAME_IN_ORL_ORP_ADVANCE_DUP = QORIQ_EVENT_BASE_DATAPATH + 724,
	QE_DPAA_PE_QM_REJECTED_LATE_FRAME_DUP = QORIQ_EVENT_BASE_DATAPATH + 725,
	QE_DPAA_PE_QM_ACCEPCTED_LATE_FRAME_DUP = QORIQ_EVENT_BASE_DATAPATH + 726,
	QE_DPAA_PE_QM_REJECTED_EARLY_FRAME_DUP = QORIQ_EVENT_BASE_DATAPATH + 727,
	
	/**********************************************/
	/* unsupported IDs: > 727 &&  < 736 */
	/**********************************************/
	
	QE_DPAA_PE_QM_SP0_ENQ_CMD_RECEIVED_DUP = QORIQ_EVENT_BASE_DATAPATH + 736,
	QE_DPAA_PE_QM_SP1_ENQ_CMD_RECEIVED_DUP = QORIQ_EVENT_BASE_DATAPATH + 737,
	QE_DPAA_PE_QM_SP2_ENQ_CMD_RECEIVED_DUP = QORIQ_EVENT_BASE_DATAPATH + 738,
	QE_DPAA_PE_QM_SP3_ENQ_CMD_RECEIVED_DUP = QORIQ_EVENT_BASE_DATAPATH + 739,
	QE_DPAA_PE_QM_SP4_ENQ_CMD_RECEIVED_DUP = QORIQ_EVENT_BASE_DATAPATH + 740,
	QE_DPAA_PE_QM_SP5_ENQ_CMD_RECEIVED_DUP = QORIQ_EVENT_BASE_DATAPATH + 741,
	QE_DPAA_PE_QM_SP6_ENQ_CMD_RECEIVED_DUP = QORIQ_EVENT_BASE_DATAPATH + 742,
	QE_DPAA_PE_QM_SP7_ENQ_CMD_RECEIVED_DUP = QORIQ_EVENT_BASE_DATAPATH + 743,
	QE_DPAA_PE_QM_SP8_ENQ_CMD_RECEIVED_DUP = QORIQ_EVENT_BASE_DATAPATH + 744,
	QE_DPAA_PE_QM_SP9_ENQ_CMD_RECEIVED_DUP = QORIQ_EVENT_BASE_DATAPATH + 745,
	QE_DPAA_PE_QM_SP0_ENQ_CMD_PULLED_EQCR_FULL_DUP = QORIQ_EVENT_BASE_DATAPATH + 746,
	QE_DPAA_PE_QM_SP1_ENQ_CMD_PULLED_EQCR_FULL_DUP = QORIQ_EVENT_BASE_DATAPATH + 747,
	QE_DPAA_PE_QM_SP2_ENQ_CMD_PULLED_EQCR_FULL_DUP = QORIQ_EVENT_BASE_DATAPATH + 748,
	QE_DPAA_PE_QM_SP3_ENQ_CMD_PULLED_EQCR_FULL_DUP = QORIQ_EVENT_BASE_DATAPATH + 749,
	QE_DPAA_PE_QM_SP4_ENQ_CMD_PULLED_EQCR_FULL_DUP = QORIQ_EVENT_BASE_DATAPATH + 750,
	QE_DPAA_PE_QM_SP5_ENQ_CMD_PULLED_EQCR_FULL_DUP = QORIQ_EVENT_BASE_DATAPATH + 751,
	QE_DPAA_PE_QM_SP6_ENQ_CMD_PULLED_EQCR_FULL_DUP = QORIQ_EVENT_BASE_DATAPATH + 752,
	QE_DPAA_PE_QM_SP7_ENQ_CMD_PULLED_EQCR_FULL_DUP = QORIQ_EVENT_BASE_DATAPATH + 753,
	QE_DPAA_PE_QM_SP8_ENQ_CMD_PULLED_EQCR_FULL_DUP = QORIQ_EVENT_BASE_DATAPATH + 754,
	QE_DPAA_PE_QM_SP9_ENQ_CMD_PULLED_EQCR_FULL_DUP = QORIQ_EVENT_BASE_DATAPATH + 755,
	QE_DPAA_PE_QM_SP0_DEQ_CMD_READY_DQRR_FULL_DUP = QORIQ_EVENT_BASE_DATAPATH + 756,
	QE_DPAA_PE_QM_SP1_DEQ_CMD_READY_DQRR_FULL_DUP = QORIQ_EVENT_BASE_DATAPATH + 757,
	QE_DPAA_PE_QM_SP2_DEQ_CMD_READY_DQRR_FULL_DUP = QORIQ_EVENT_BASE_DATAPATH + 758,
	QE_DPAA_PE_QM_SP3_DEQ_CMD_READY_DQRR_FULL_DUP = QORIQ_EVENT_BASE_DATAPATH + 759,
	QE_DPAA_PE_QM_SP4_DEQ_CMD_READY_DQRR_FULL_DUP = QORIQ_EVENT_BASE_DATAPATH + 760,
	QE_DPAA_PE_QM_SP5_DEQ_CMD_READY_DQRR_FULL_DUP = QORIQ_EVENT_BASE_DATAPATH + 761,
	QE_DPAA_PE_QM_SP6_DEQ_CMD_READY_DQRR_FULL_DUP = QORIQ_EVENT_BASE_DATAPATH + 762,
	QE_DPAA_PE_QM_SP7_DEQ_CMD_READY_DQRR_FULL_DUP = QORIQ_EVENT_BASE_DATAPATH + 763,
	QE_DPAA_PE_QM_SP8_DEQ_CMD_READY_DQRR_FULL_DUP = QORIQ_EVENT_BASE_DATAPATH + 764,
	QE_DPAA_PE_QM_SP9_DEQ_CMD_READY_DQRR_FULL_DUP = QORIQ_EVENT_BASE_DATAPATH + 765,

	QORIQ_EVENT_DATAPATH_LAST = QE_DPAA_PE_QM_SP9_DEQ_CMD_READY_DQRR_FULL_DUP,

	/************************************************************/
	/* DDR events 												*/
	/************************************************************/
	QORIQ_EVENT_DDR_FIRST = QORIQ_EVENT_BASE_DDR + 0x0,
			
	QE_DDR1_READ_CYCLES = QORIQ_EVENT_DDR_FIRST + 0,
	QE_DDR1_WRITE_CYCLES = QORIQ_EVENT_BASE_DDR + 1,
	QE_DDR1_PAGE_CLOSING_NON_REFRESH = QORIQ_EVENT_BASE_DDR + 2,
	QE_DDR1_PAGE_CLOSING = QORIQ_EVENT_BASE_DDR + 3,
	QE_DDR1_PAGE_CLOSING_COLLISION = QORIQ_EVENT_BASE_DDR + 4,
	QE_DDR1_DIVIDE_BY_4_DDRC_CLOCK_PULSE = QORIQ_EVENT_BASE_DDR + 5, //New

	
	/**********************************************/
	/* unsupported IDs: > 5 &&  <  256 */
	/**********************************************/
	
	QE_DDR2_READ_CYCLES = QORIQ_EVENT_BASE_DDR + 256,
	QE_DDR2_WRITE_CYCLES = QORIQ_EVENT_BASE_DDR + 257,
	QE_DDR2_PAGE_CLOSING_NON_REFRESH = QORIQ_EVENT_BASE_DDR + 258,
	QE_DDR2_PAGE_CLOSING = QORIQ_EVENT_BASE_DDR + 259,
	QE_DDR2_PAGE_CLOSING_COLLISION = QORIQ_EVENT_BASE_DDR + 260,
	QE_DDR2_DIVIDE_BY_4_DDRC_CLOCK_PULSE = QORIQ_EVENT_BASE_DDR + 261,  //New
	/**********************************************/
	/* unsupported IDs: > 265 &&  <  512 */
	/**********************************************/

	/* Only B4860 uses only 2 DDRs 

	QE_DDR3_READ_CYCLES = QORIQ_EVENT_BASE_DDR + 512,//New
	QE_DDR3_WRITE_CYCLES = QORIQ_EVENT_BASE_DDR + 513,//New
	QE_DDR3_PAGE_CLOSING_NON_REFRESH = QORIQ_EVENT_BASE_DDR + 514,//New
	QE_DDR3_PAGE_CLOSING = QORIQ_EVENT_BASE_DDR + 515,//New
	QE_DDR3_PAGE_CLOSING_COLLISION = QORIQ_EVENT_BASE_DDR + 516,//New
	QE_DDR3_DIVIDE_BY_4_DDRC_CLOCK_PULSE = QORIQ_EVENT_BASE_DDR + 517,  //New
	*/
	/**********************************************/
	/* unsupported IDs: > 517 &&  <  768 */
	/**********************************************/
/* Only B4860 uses only 2 DDRs 
	
	QE_DDR4_READ_CYCLES = QORIQ_EVENT_BASE_DDR + 768,//New
	QE_DDR4_WRITE_CYCLES = QORIQ_EVENT_BASE_DDR + 769,//New
	QE_DDR4_PAGE_CLOSING_NON_REFRESH = QORIQ_EVENT_BASE_DDR + 770,//New
	QE_DDR4_PAGE_CLOSING = QORIQ_EVENT_BASE_DDR + 771,//New
	QE_DDR4_PAGE_CLOSING_COLLISION = QORIQ_EVENT_BASE_DDR + 772,//New
	QE_DDR4_DIVIDE_BY_4_DDRC_CLOCK_PULSE = QORIQ_EVENT_BASE_DDR + 773,  //New
	
	QORIQ_EVENT_DDR_LAST = QE_DDR4_DIVIDE_BY_4_DDRC_CLOCK_PULSE,
*/
	QORIQ_EVENT_DDR_LAST = QE_DDR2_DIVIDE_BY_4_DDRC_CLOCK_PULSE,
	
	/************************************************************/
	/* NPC events 												*/
	/************************************************************/
	QORIQ_EVENT_NPC_FIRST = QORIQ_EVENT_BASE_NPC + 0x0,
	
	QE_NPC_QWRITE = QORIQ_EVENT_NPC_FIRST,
	QE_NPC_TGT_REGION_FULL,
	QE_NPC_TRBFR_FULL,
	QE_NPC_EV_OUT,
	QE_NPC_MMA_DONE,

	QORIQ_EVENT_NPC_LAST = QE_NPC_MMA_DONE,
	
	/************************************************************/
	/* Complex, Class 1, DDR events 							*/
	/* no source filtering 										*/
	/************************************************************/
	QORIQ_EVENT_DDR_COMPLEX_FIRST = QORIQ_EVENT_BASE_DDR_COMPLEX + 0x0,
	
	QE_DDR1_PAGE_HIT = QORIQ_EVENT_DDR_COMPLEX_FIRST,
	QE_DDR1_PAGE_MISS,
	QE_DDR2_PAGE_HIT,
	QE_DDR2_PAGE_MISS,
	
	QORIQ_EVENT_DDR_COMPLEX_LAST = QE_DDR2_PAGE_MISS,	
};

int qoriq_is_valid_event(unsigned int evt_num);


#endif /* QORIQ_RAW_EVENTS_H */
